apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: erato-dev
servers: 1
agents: 0
image: "rancher/k3s:v1.34.1-k3s1"
registries:
  create:
    name: k3d-registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
    volumes:
      - /tmp/k3d-erato-registry-data:/var/lib/registry
  config: |
    mirrors:
      "k3d-registry.localhost:5000":
        endpoint:
          - http://k3d-registry.localhost:5000
      "docker.io":
        endpoint:
          - http://k3d-registry.localhost:5000
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=eviction-hard=imagefs.available<0.5%,nodefs.available<0.5%
        nodeFilters:
          - server:*
          - agent:*
      - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=0.5%,nodefs.available=0.5%
        nodeFilters:
          - server:*
          - agent:* 