apiVersion: v2
name: erato
description: Helm chart for the Erato chat application
type: application
version: 0.6.2
appVersion: 0.6.2
keywords:
- ai
- llm
- chat
- web-ui
- mcp
maintainers:
- name: Erato Team
- name: Maximilian Goisser
  email: max@eratolabs.com
home: https://erato.chat
icon: https://erato.chat/erato_logo.svg
sources:
- https://github.com/EratoLab/erato/tree/main/infrastructure/charts/erato
- https://github.com/EratoLab/erato
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/links: "- name: Repository\n  url: https://github.com/EratoLab/erato\n\
    - name: Chart in repository\n  url: https://github.com/EratoLab/erato/tree/main/infrastructure/charts/erato\n"
dependencies:
- name: common
  version: 2.30.0
  repository: oci://registry-1.docker.io/bitnamicharts
