default:
    just --list

storybook:
    pnpm run storybook

install:
    pnpm install

dev:
    pnpm run dev

start:
    pnpm run start

format:
    pnpm exec prettier . --write

lint:
    pnpm run lint