default:
    just --list

storybook:
    pnpm run storybook

# Generate the OpenAPI client based on the OpenAPI spec in the backend.
codegen:
    pnpm run codegen

install:
    pnpm install

dev:
    pnpm run dev

start:
    pnpm run start

format:
    pnpm exec prettier . --write

check-format:
    pnpm exec prettier . --check

lint:
    pnpm run lint