default:
    just --list

storybook:
    pnpm run storybook

# Generate the OpenAPI client based on the OpenAPI spec in the backend.
codegen:
    pnpm run codegen

install:
    pnpm install

dev:
    cd local-auth && docker compose up --force-recreate --detach
    echo "Proxied local server with auth will be available at http://localhost:4180"
    pnpm run dev

start:
    pnpm run start

format:
    pnpm exec prettier . --write

check-format:
    pnpm exec prettier . --check

lint:
    pnpm run lint
