default:
    just --list

install_clis:
    cargo install sea-orm-cli@1.1.4

generate_db_schema:
    sea-orm-cli generate entity -u postgres://eratouser:eratopw@localhost:5432/erato -o src/db/entity

test:
    cargo test

lint:
    echo "Linitng not implemented yet"