version: "3.7"

services:
  oauth2-proxy:
    # https://github.com/oauth2-proxy/oauth2-proxy/releases
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1
    network_mode: host
    volumes:
      - ./oauth2-proxy-entra-id.cfg:/etc/oauth2-proxy/oauth2-proxy.cfg
    command: ["--config", "/etc/oauth2-proxy/oauth2-proxy.cfg"]
