default:
    just --list

install:
    pnpm install

run:
    pnpm run dev

build:
    pnpm run build

build_and_serve:
    pnpm run build
    pnpm exec serve out -p 54624

format:
    pnpm exec prettier . --write

check-format:
    pnpm exec prettier . --check
