# Global settings
global:
  environment: development

# Backend configuration
backend:
  name: backend
  image:
    repository: peknow/backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 8080

# Frontend configuration
frontend:
  name: frontend
  image:
    repository: peknow/frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 80

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: peknow.local
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: peknow
    database: peknow
  primary:
    persistence:
      size: 1Gi 