-- ============================================================================
-- Database Schema Dump
-- Generated by dump_current_schema.sh
-- Database: erato
-- Schema: public
-- Excluded tables: changes dependencies events projects releases tags
-- ============================================================================

--
-- PostgreSQL database dump
--

\restrict np6fMCKvEDxceIEhwPMvNotTcZpCy5hefQkwTPQqcdX1qxA3DZBZCfCWI21S8e8

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'Sqitch database deployment metadata v1.1.';


--
-- Name: check_active_thread_siblings_constraint(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.check_active_thread_siblings_constraint() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    affected_group_ids uuid[];
    violation_found boolean;
BEGIN
    affected_group_ids := array_remove(
        ARRAY[
            COALESCE(NEW.sibling_message_id, NEW.id),
            CASE
                WHEN TG_OP = 'UPDATE' THEN COALESCE(OLD.sibling_message_id, OLD.id)
                ELSE NULL
            END
        ],
        NULL
    );

    -- Only validate the sibling groups touched by this row.
    SELECT EXISTS (
        WITH active_counts AS (
            SELECT
                COALESCE(sibling_message_id, id) AS group_id,
                SUM(CASE WHEN is_message_in_active_thread THEN 1 ELSE 0 END) AS active_count
            FROM public.messages
            WHERE
                id = ANY(affected_group_ids)
                OR sibling_message_id = ANY(affected_group_ids)
            GROUP BY COALESCE(sibling_message_id, id)
        )
        SELECT 1
        FROM active_counts
        WHERE active_count > 1
        LIMIT 1
    ) INTO violation_found;
    
    IF violation_found THEN
        RAISE EXCEPTION 'Constraint violation: Multiple messages in the same sibling group are marked as active';
    END IF;
    
    RETURN NULL;
END;
$$;


--
-- Name: set_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$;


--
-- Name: uuidv7(timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.uuidv7(timestamp with time zone DEFAULT clock_timestamp()) RETURNS uuid
    LANGUAGE sql PARALLEL SAFE
    AS $_$
  -- Replace the first 48 bits of a uuidv4 with the current
  -- number of milliseconds since 1970-01-01 UTC
  -- and set the "ver" field to 7 by setting additional bits
  select encode(
    set_bit(
      set_bit(
        overlay(uuid_send(gen_random_uuid()) placing
	  substring(int8send((extract(epoch from $1)*1000)::bigint) from 3)
	  from 1 for 6),
	52, 1),
      53, 1), 'hex')::uuid;
$_$;


SET default_table_access_method = heap;

--
-- Name: assistant_file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistant_file_uploads (
    assistant_id uuid NOT NULL,
    file_upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: assistants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistants (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    owner_user_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    prompt text NOT NULL,
    mcp_server_ids text[],
    default_chat_provider text,
    archived_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    facet_ids text[],
    enforce_facet_settings boolean DEFAULT false NOT NULL
);


--
-- Name: chat_file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_file_uploads (
    chat_id uuid NOT NULL,
    file_upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chats (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    owner_user_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    title_by_summary text,
    archived_at timestamp with time zone,
    assistant_configuration jsonb,
    assistant_id uuid GENERATED ALWAYS AS (((assistant_configuration ->> 'assistant_id'::text))::uuid) STORED,
    title_by_user_provided text
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    chat_id uuid NOT NULL,
    raw_message jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    previous_message_id uuid,
    sibling_message_id uuid,
    is_message_in_active_thread boolean DEFAULT true NOT NULL,
    generation_input_messages jsonb,
    input_file_uploads uuid[],
    generation_parameters jsonb,
    generation_metadata jsonb
);


--
-- Name: chats_latest_message; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.chats_latest_message AS
 SELECT chat_id,
    id AS latest_message_id,
    created_at AS latest_message_at
   FROM ( SELECT m.chat_id,
            m.id,
            m.created_at,
            row_number() OVER (PARTITION BY m.chat_id ORDER BY m.created_at DESC) AS rn
           FROM public.messages m) ranked_messages
  WHERE (rn = 1);


--
-- Name: file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_uploads (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    filename text NOT NULL,
    file_storage_provider_id text NOT NULL,
    file_storage_path text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    owner_user_id text NOT NULL
);


--
-- Name: message_feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_feedbacks (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    message_id uuid NOT NULL,
    sentiment text NOT NULL,
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT message_feedbacks_sentiment_check CHECK ((sentiment = ANY (ARRAY['positive'::text, 'negative'::text])))
);


--
-- Name: share_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share_grants (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    subject_type text NOT NULL,
    subject_id_type text NOT NULL,
    subject_id text NOT NULL,
    role text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_daily_token_usage; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.user_daily_token_usage AS
 SELECT c.owner_user_id AS user_id,
    date(m.created_at) AS usage_date,
    COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text) AS chat_provider_id,
    count(*) AS total_messages,
    sum(COALESCE(((m.generation_metadata ->> 'used_prompt_tokens'::text))::integer, 0)) AS total_prompt_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_completion_tokens'::text))::integer, 0)) AS total_completion_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_total_tokens'::text))::integer, 0)) AS total_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_reasoning_tokens'::text))::integer, 0)) AS total_reasoning_tokens
   FROM (public.messages m
     JOIN public.chats c ON ((m.chat_id = c.id)))
  WHERE ((m.generation_metadata IS NOT NULL) AND (m.generation_metadata ? 'used_total_tokens'::text))
  GROUP BY c.owner_user_id, (date(m.created_at)), COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text)
  ORDER BY (date(m.created_at)) DESC, c.owner_user_id, COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    user_id uuid NOT NULL,
    nickname text,
    job_title text,
    assistant_custom_instructions text,
    assistant_additional_information text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    issuer text NOT NULL,
    subject text NOT NULL,
    email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: COLUMN users.issuer; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.issuer IS 'The identity provider (IdP) that authenticated the user (e.g., ''https://login.microsoftonline.com/'', ''https://accounts.google.com'')';


--
-- Name: COLUMN users.subject; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.subject IS 'The unique identifier for the user at the IdP (usually a UUID or similar)';


--
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.email IS 'The user''s email address (optional, as not all IdPs may provide it)';


--
-- Name: assistant_file_uploads assistant_file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_pkey PRIMARY KEY (assistant_id, file_upload_id);


--
-- Name: assistants assistants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistants
    ADD CONSTRAINT assistants_pkey PRIMARY KEY (id);


--
-- Name: chat_file_uploads chat_file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_pkey PRIMARY KEY (chat_id, file_upload_id);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);


--
-- Name: file_uploads file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_uploads
    ADD CONSTRAINT file_uploads_pkey PRIMARY KEY (id);


--
-- Name: message_feedbacks message_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_pkey PRIMARY KEY (id);


--
-- Name: message_feedbacks message_feedbacks_unique_message; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_unique_message UNIQUE (message_id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: share_grants share_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_grants
    ADD CONSTRAINT share_grants_pkey PRIMARY KEY (id);


--
-- Name: share_grants share_grants_unique_grant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_grants
    ADD CONSTRAINT share_grants_unique_grant UNIQUE (resource_type, resource_id, subject_type, subject_id_type, subject_id, role);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_assistant_file_uploads_assistant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_file_uploads_assistant_id ON public.assistant_file_uploads USING btree (assistant_id);


--
-- Name: idx_assistant_file_uploads_file_upload_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_file_uploads_file_upload_id ON public.assistant_file_uploads USING btree (file_upload_id);


--
-- Name: idx_assistants_archived_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_archived_at ON public.assistants USING btree (archived_at);


--
-- Name: idx_assistants_owner_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_owner_user_id ON public.assistants USING btree (owner_user_id);


--
-- Name: idx_assistants_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_updated_at ON public.assistants USING btree (updated_at DESC);


--
-- Name: idx_chat_file_uploads_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_file_uploads_chat_id ON public.chat_file_uploads USING btree (chat_id);


--
-- Name: idx_chat_file_uploads_file_upload_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_file_uploads_file_upload_id ON public.chat_file_uploads USING btree (file_upload_id);


--
-- Name: idx_chats_assistant_configuration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_assistant_configuration ON public.chats USING btree (((assistant_configuration ->> 'assistant_id'::text)));


--
-- Name: idx_file_uploads_owner_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_uploads_owner_user_id ON public.file_uploads USING btree (owner_user_id);


--
-- Name: idx_message_feedbacks_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_feedbacks_created_at ON public.message_feedbacks USING btree (created_at DESC);


--
-- Name: idx_message_feedbacks_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_feedbacks_message_id ON public.message_feedbacks USING btree (message_id);


--
-- Name: idx_messages_active_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_active_thread ON public.messages USING btree (is_message_in_active_thread) WHERE (is_message_in_active_thread = true);


--
-- Name: idx_messages_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_chat_id ON public.messages USING btree (chat_id);


--
-- Name: idx_messages_previous_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_previous_message_id ON public.messages USING btree (previous_message_id);


--
-- Name: idx_messages_sibling_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_sibling_message_id ON public.messages USING btree (sibling_message_id);


--
-- Name: idx_share_grants_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_created_at ON public.share_grants USING btree (created_at DESC);


--
-- Name: idx_share_grants_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_resource ON public.share_grants USING btree (resource_type, resource_id);


--
-- Name: idx_share_grants_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_subject ON public.share_grants USING btree (subject_type, subject_id_type, subject_id);


--
-- Name: idx_users_issuer_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_issuer_subject ON public.users USING btree (issuer, subject);


--
-- Name: messages ensure_single_active_message_in_thread; Type: TRIGGER; Schema: public; Owner: -
--

CREATE CONSTRAINT TRIGGER ensure_single_active_message_in_thread AFTER INSERT OR UPDATE ON public.messages DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.check_active_thread_siblings_constraint();


--
-- Name: chats on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.chats FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: file_uploads on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: messages on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: users on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_file_uploads on_update_set_updated_columns_assistant_file_uploads; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistant_file_uploads BEFORE UPDATE ON public.assistant_file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistants on_update_set_updated_columns_assistants; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistants BEFORE UPDATE ON public.assistants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: chat_file_uploads on_update_set_updated_columns_chat_file_uploads; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_chat_file_uploads BEFORE UPDATE ON public.chat_file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: message_feedbacks on_update_set_updated_columns_message_feedbacks; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_message_feedbacks BEFORE UPDATE ON public.message_feedbacks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: share_grants on_update_set_updated_columns_share_grants; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_share_grants BEFORE UPDATE ON public.share_grants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: user_preferences set_updated_at_column; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at_column BEFORE UPDATE ON public.user_preferences FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_file_uploads assistant_file_uploads_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_file_uploads assistant_file_uploads_file_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_file_upload_id_fkey FOREIGN KEY (file_upload_id) REFERENCES public.file_uploads(id) ON DELETE CASCADE;


--
-- Name: assistants assistants_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistants
    ADD CONSTRAINT assistants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: chat_file_uploads chat_file_uploads_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: chat_file_uploads chat_file_uploads_file_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_file_upload_id_fkey FOREIGN KEY (file_upload_id) REFERENCES public.file_uploads(id) ON DELETE CASCADE;


--
-- Name: chats chats_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id);


--
-- Name: message_feedbacks message_feedbacks_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: messages messages_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id);


--
-- Name: messages messages_previous_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_previous_message_id_fkey FOREIGN KEY (previous_message_id) REFERENCES public.messages(id);


--
-- Name: messages messages_sibling_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_sibling_message_id_fkey FOREIGN KEY (sibling_message_id) REFERENCES public.messages(id);


--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict np6fMCKvEDxceIEhwPMvNotTcZpCy5hefQkwTPQqcdX1qxA3DZBZCfCWI21S8e8
