-- ============================================================================
-- Database Schema Dump
-- Generated by dump_current_schema.sh
-- Database: schema_dump_tmp
-- Schema: public
-- Excluded tables: changes dependencies events projects releases tags
-- ============================================================================

--
-- PostgreSQL database dump
--

\restrict OM7cNXdBdyBvLZvgpYZtJmnVfBbiARdfWSfbAR86ERODzDTyXhtRLbkmz7CSgJk

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: check_active_thread_siblings_constraint(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.check_active_thread_siblings_constraint() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    affected_group_ids uuid[];
    violation_found boolean;
BEGIN
    affected_group_ids := array_remove(
        ARRAY[
            COALESCE(NEW.sibling_message_id, NEW.id),
            CASE
                WHEN TG_OP = 'UPDATE' THEN COALESCE(OLD.sibling_message_id, OLD.id)
                ELSE NULL
            END
        ],
        NULL
    );

    -- Only validate the sibling groups touched by this row.
    SELECT EXISTS (
        WITH active_counts AS (
            SELECT
                COALESCE(sibling_message_id, id) AS group_id,
                SUM(CASE WHEN is_message_in_active_thread THEN 1 ELSE 0 END) AS active_count
            FROM public.messages
            WHERE
                id = ANY(affected_group_ids)
                OR sibling_message_id = ANY(affected_group_ids)
            GROUP BY COALESCE(sibling_message_id, id)
        )
        SELECT 1
        FROM active_counts
        WHERE active_count > 1
        LIMIT 1
    ) INTO violation_found;

    IF violation_found THEN
        RAISE EXCEPTION 'Constraint violation: Multiple messages in the same sibling group are marked as active';
    END IF;

    RETURN NULL;
END;
$$;


--
-- Name: set_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$;


--
-- Name: uuidv7(timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.uuidv7(timestamp with time zone DEFAULT clock_timestamp()) RETURNS uuid
    LANGUAGE sql PARALLEL SAFE
    AS $_$
  -- Replace the first 48 bits of a uuidv4 with the current
  -- number of milliseconds since 1970-01-01 UTC
  -- and set the "ver" field to 7 by setting additional bits
  select encode(
    set_bit(
      set_bit(
        overlay(uuid_send(gen_random_uuid()) placing
	  substring(int8send((extract(epoch from $1)*1000)::bigint) from 3)
	  from 1 for 6),
	52, 1),
      53, 1), 'hex')::uuid;
$_$;


SET default_table_access_method = heap;

--
-- Name: assistant_file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistant_file_uploads (
    assistant_id uuid NOT NULL,
    file_upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: assistant_hub_assistant_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistant_hub_assistant_versions (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    assistant_hub_assistant_id uuid NOT NULL,
    assistant_id uuid NOT NULL,
    status text NOT NULL,
    is_published boolean DEFAULT false NOT NULL,
    is_current_published_version boolean DEFAULT false NOT NULL,
    version_number text NOT NULL,
    version_comment text,
    creator_review_comment text,
    reviewer_review_comment text,
    long_description text NOT NULL,
    category_ids text[],
    keywords text[],
    diff_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewed_at timestamp with time zone,
    withdrawn_at timestamp with time zone,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT assistant_hub_assistant_versions_current_published_check CHECK (((NOT is_current_published_version) OR (is_published AND (status = 'review_accepted'::text)))),
    CONSTRAINT assistant_hub_assistant_versions_published_status_check CHECK (((NOT is_published) OR (status = 'review_accepted'::text))),
    CONSTRAINT assistant_hub_assistant_versions_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'review_accepted'::text, 'review_declined'::text, 'withdrawn'::text])))
);


--
-- Name: assistant_hub_assistants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistant_hub_assistants (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    source_assistant_id uuid NOT NULL,
    owner_user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    featured boolean DEFAULT false NOT NULL
);


--
-- Name: assistant_hub_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistant_hub_reviews (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    assistant_hub_assistant_id uuid NOT NULL,
    assistant_hub_assistant_version_id uuid NOT NULL,
    reviewer_user_id uuid NOT NULL,
    score integer NOT NULL,
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT assistant_hub_reviews_score_check CHECK (((score >= 1) AND (score <= 10)))
);


--
-- Name: assistants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assistants (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    owner_user_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    prompt text NOT NULL,
    mcp_server_ids text[],
    default_chat_provider text,
    archived_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    facet_ids text[],
    enforce_facet_settings boolean DEFAULT false NOT NULL
);


--
-- Name: chat_file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_file_uploads (
    chat_id uuid NOT NULL,
    file_upload_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chats (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    owner_user_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    title_by_summary text,
    archived_at timestamp with time zone,
    assistant_configuration jsonb,
    assistant_id uuid GENERATED ALWAYS AS (((assistant_configuration ->> 'assistant_id'::text))::uuid) STORED,
    title_by_user_provided text,
    active_generation_id uuid,
    generation_state text,
    generation_started_at timestamp with time zone,
    generation_heartbeat_at timestamp with time zone,
    generation_ended_at timestamp with time zone,
    is_pinned boolean DEFAULT false NOT NULL,
    origin_chat_id uuid GENERATED ALWAYS AS (((assistant_configuration #>> '{provenance,origin_chat_id}'::text[]))::uuid) STORED
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    chat_id uuid NOT NULL,
    raw_message jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    previous_message_id uuid,
    sibling_message_id uuid,
    is_message_in_active_thread boolean DEFAULT true NOT NULL,
    generation_input_messages jsonb,
    input_file_uploads uuid[],
    generation_parameters jsonb,
    generation_metadata jsonb,
    input_parameters jsonb
);


--
-- Name: chats_latest_message; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.chats_latest_message AS
 SELECT chat_id,
    id AS latest_message_id,
    created_at AS latest_message_at
   FROM ( SELECT m.chat_id,
            m.id,
            m.created_at,
            row_number() OVER (PARTITION BY m.chat_id ORDER BY m.created_at DESC) AS rn
           FROM public.messages m) ranked_messages
  WHERE (rn = 1);


--
-- Name: file_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_uploads (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    filename text NOT NULL,
    file_storage_provider_id text NOT NULL,
    file_storage_path text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    owner_user_id text NOT NULL,
    audio_transcription text
);


--
-- Name: mcp_server_oauth_authorization_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mcp_server_oauth_authorization_states (
    user_id uuid NOT NULL,
    mcp_server_id text NOT NULL,
    csrf_token text NOT NULL,
    state_encrypted text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: mcp_server_oauth_clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mcp_server_oauth_clients (
    mcp_server_id text NOT NULL,
    client_id text NOT NULL,
    client_secret_encrypted text,
    redirect_uri text NOT NULL,
    registration_metadata jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: mcp_server_oauth_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mcp_server_oauth_credentials (
    user_id uuid NOT NULL,
    mcp_server_id text NOT NULL,
    credentials_encrypted text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone
);


--
-- Name: message_feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_feedbacks (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    message_id uuid NOT NULL,
    sentiment text NOT NULL,
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT message_feedbacks_sentiment_check CHECK ((sentiment = ANY (ARRAY['positive'::text, 'negative'::text])))
);


--
-- Name: runtime_configuration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runtime_configuration (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    source_service text NOT NULL,
    source_filename text,
    config text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    source_type text DEFAULT 'erato_toml'::text NOT NULL
);


--
-- Name: share_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share_grants (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    subject_type text NOT NULL,
    subject_id_type text NOT NULL,
    subject_id text NOT NULL,
    role text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: share_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share_links (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: temp_chat_generation_commands; Type: TABLE; Schema: public; Owner: -
--

CREATE UNLOGGED TABLE public.temp_chat_generation_commands (
    command_id bigint NOT NULL,
    generation_id uuid NOT NULL,
    command_type text NOT NULL,
    tool_call_id text,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    consumed_at timestamp with time zone
);


--
-- Name: temp_chat_generation_commands_command_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.temp_chat_generation_commands ALTER COLUMN command_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.temp_chat_generation_commands_command_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: temp_chat_generation_events; Type: TABLE; Schema: public; Owner: -
--

CREATE UNLOGGED TABLE public.temp_chat_generation_events (
    event_id bigint NOT NULL,
    generation_id uuid NOT NULL,
    event jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: temp_chat_generation_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.temp_chat_generation_events ALTER COLUMN event_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.temp_chat_generation_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: temp_chat_generations; Type: TABLE; Schema: public; Owner: -
--

CREATE UNLOGGED TABLE public.temp_chat_generations (
    generation_id uuid NOT NULL,
    chat_id uuid NOT NULL,
    message_id uuid,
    owner_pod text NOT NULL,
    state text DEFAULT 'running'::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    heartbeat_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone
);


--
-- Name: user_daily_token_usage; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.user_daily_token_usage AS
 SELECT c.owner_user_id AS user_id,
    date(m.created_at) AS usage_date,
    COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text) AS chat_provider_id,
    count(*) AS total_messages,
    sum(COALESCE(((m.generation_metadata ->> 'used_prompt_tokens'::text))::integer, 0)) AS total_prompt_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_completion_tokens'::text))::integer, 0)) AS total_completion_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_total_tokens'::text))::integer, 0)) AS total_tokens,
    sum(COALESCE(((m.generation_metadata ->> 'used_reasoning_tokens'::text))::integer, 0)) AS total_reasoning_tokens
   FROM (public.messages m
     JOIN public.chats c ON ((m.chat_id = c.id)))
  WHERE ((m.generation_metadata IS NOT NULL) AND (m.generation_metadata ? 'used_total_tokens'::text))
  GROUP BY c.owner_user_id, (date(m.created_at)), COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text)
  ORDER BY (date(m.created_at)) DESC, c.owner_user_id, COALESCE((m.generation_parameters ->> 'generation_chat_provider_id'::text), 'unknown'::text);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    user_id uuid NOT NULL,
    nickname text,
    job_title text,
    assistant_custom_instructions text,
    assistant_additional_information text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    default_chat_provider text,
    starting_hub_assistant_id uuid,
    starting_assistant_cleared boolean DEFAULT false NOT NULL,
    CONSTRAINT user_preferences_starting_assistant_state_check CHECK ((NOT (starting_assistant_cleared AND (starting_hub_assistant_id IS NOT NULL))))
);


--
-- Name: user_tool_approval_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_tool_approval_settings (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    mcp_server_id text NOT NULL,
    tool_name text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deactivated_at timestamp with time zone
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuidv7() NOT NULL,
    issuer text NOT NULL,
    subject text NOT NULL,
    email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: COLUMN users.issuer; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.issuer IS 'The identity provider (IdP) that authenticated the user (e.g., ''https://login.microsoftonline.com/'', ''https://accounts.google.com'')';


--
-- Name: COLUMN users.subject; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.subject IS 'The unique identifier for the user at the IdP (usually a UUID or similar)';


--
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.email IS 'The user''s email address (optional, as not all IdPs may provide it)';


--
-- Name: assistant_file_uploads assistant_file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_pkey PRIMARY KEY (assistant_id, file_upload_id);


--
-- Name: assistant_hub_assistant_versions assistant_hub_assistant_versions_assistant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistant_versions
    ADD CONSTRAINT assistant_hub_assistant_versions_assistant_id_key UNIQUE (assistant_id);


--
-- Name: assistant_hub_assistant_versions assistant_hub_assistant_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistant_versions
    ADD CONSTRAINT assistant_hub_assistant_versions_pkey PRIMARY KEY (id);


--
-- Name: assistant_hub_assistants assistant_hub_assistants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistants
    ADD CONSTRAINT assistant_hub_assistants_pkey PRIMARY KEY (id);


--
-- Name: assistant_hub_assistants assistant_hub_assistants_source_assistant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistants
    ADD CONSTRAINT assistant_hub_assistants_source_assistant_id_key UNIQUE (source_assistant_id);


--
-- Name: assistant_hub_reviews assistant_hub_reviews_assistant_reviewer_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_reviews
    ADD CONSTRAINT assistant_hub_reviews_assistant_reviewer_key UNIQUE (assistant_hub_assistant_id, reviewer_user_id);


--
-- Name: assistant_hub_reviews assistant_hub_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_reviews
    ADD CONSTRAINT assistant_hub_reviews_pkey PRIMARY KEY (id);


--
-- Name: assistants assistants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistants
    ADD CONSTRAINT assistants_pkey PRIMARY KEY (id);


--
-- Name: chat_file_uploads chat_file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_pkey PRIMARY KEY (chat_id, file_upload_id);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);


--
-- Name: file_uploads file_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_uploads
    ADD CONSTRAINT file_uploads_pkey PRIMARY KEY (id);


--
-- Name: mcp_server_oauth_authorization_states mcp_server_oauth_authorization_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_server_oauth_authorization_states
    ADD CONSTRAINT mcp_server_oauth_authorization_states_pkey PRIMARY KEY (user_id, mcp_server_id, csrf_token);


--
-- Name: mcp_server_oauth_clients mcp_server_oauth_clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_server_oauth_clients
    ADD CONSTRAINT mcp_server_oauth_clients_pkey PRIMARY KEY (mcp_server_id);


--
-- Name: mcp_server_oauth_credentials mcp_server_oauth_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_server_oauth_credentials
    ADD CONSTRAINT mcp_server_oauth_credentials_pkey PRIMARY KEY (user_id, mcp_server_id);


--
-- Name: message_feedbacks message_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_pkey PRIMARY KEY (id);


--
-- Name: message_feedbacks message_feedbacks_unique_message; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_unique_message UNIQUE (message_id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: runtime_configuration runtime_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runtime_configuration
    ADD CONSTRAINT runtime_configuration_pkey PRIMARY KEY (id);


--
-- Name: share_grants share_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_grants
    ADD CONSTRAINT share_grants_pkey PRIMARY KEY (id);


--
-- Name: share_grants share_grants_unique_grant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_grants
    ADD CONSTRAINT share_grants_unique_grant UNIQUE (resource_type, resource_id, subject_type, subject_id_type, subject_id, role);


--
-- Name: share_links share_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_pkey PRIMARY KEY (id);


--
-- Name: share_links share_links_unique_resource; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_unique_resource UNIQUE (resource_type, resource_id);


--
-- Name: temp_chat_generation_commands temp_chat_generation_commands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generation_commands
    ADD CONSTRAINT temp_chat_generation_commands_pkey PRIMARY KEY (command_id);


--
-- Name: temp_chat_generation_events temp_chat_generation_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generation_events
    ADD CONSTRAINT temp_chat_generation_events_pkey PRIMARY KEY (event_id);


--
-- Name: temp_chat_generations temp_chat_generations_chat_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generations
    ADD CONSTRAINT temp_chat_generations_chat_key UNIQUE (chat_id);


--
-- Name: temp_chat_generations temp_chat_generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generations
    ADD CONSTRAINT temp_chat_generations_pkey PRIMARY KEY (generation_id);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);


--
-- Name: user_tool_approval_settings user_tool_approval_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tool_approval_settings
    ADD CONSTRAINT user_tool_approval_settings_pkey PRIMARY KEY (id);


--
-- Name: user_tool_approval_settings user_tool_approval_settings_user_server_tool_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tool_approval_settings
    ADD CONSTRAINT user_tool_approval_settings_user_server_tool_key UNIQUE (user_id, mcp_server_id, tool_name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: chats_generation_state_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chats_generation_state_idx ON public.chats USING btree (owner_user_id) WHERE (generation_state IS NOT NULL);


--
-- Name: idx_assistant_file_uploads_assistant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_file_uploads_assistant_id ON public.assistant_file_uploads USING btree (assistant_id);


--
-- Name: idx_assistant_file_uploads_file_upload_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_file_uploads_file_upload_id ON public.assistant_file_uploads USING btree (file_upload_id);


--
-- Name: idx_assistant_hub_assistants_featured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_assistants_featured ON public.assistant_hub_assistants USING btree (featured) WHERE featured;


--
-- Name: idx_assistant_hub_assistants_owner_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_assistants_owner_user_id ON public.assistant_hub_assistants USING btree (owner_user_id);


--
-- Name: idx_assistant_hub_reviews_hub_assistant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_reviews_hub_assistant_id ON public.assistant_hub_reviews USING btree (assistant_hub_assistant_id);


--
-- Name: idx_assistant_hub_reviews_reviewer_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_reviews_reviewer_user_id ON public.assistant_hub_reviews USING btree (reviewer_user_id);


--
-- Name: idx_assistant_hub_reviews_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_reviews_version_id ON public.assistant_hub_reviews USING btree (assistant_hub_assistant_version_id);


--
-- Name: idx_assistant_hub_versions_category_ids; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_versions_category_ids ON public.assistant_hub_assistant_versions USING gin (category_ids);


--
-- Name: idx_assistant_hub_versions_current; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_assistant_hub_versions_current ON public.assistant_hub_assistant_versions USING btree (assistant_hub_assistant_id) WHERE is_current_published_version;


--
-- Name: idx_assistant_hub_versions_hub_assistant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_versions_hub_assistant_id ON public.assistant_hub_assistant_versions USING btree (assistant_hub_assistant_id);


--
-- Name: idx_assistant_hub_versions_keywords; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_versions_keywords ON public.assistant_hub_assistant_versions USING gin (keywords);


--
-- Name: idx_assistant_hub_versions_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_versions_published ON public.assistant_hub_assistant_versions USING btree (is_published, is_current_published_version);


--
-- Name: idx_assistant_hub_versions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistant_hub_versions_status ON public.assistant_hub_assistant_versions USING btree (status);


--
-- Name: idx_assistants_archived_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_archived_at ON public.assistants USING btree (archived_at);


--
-- Name: idx_assistants_owner_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_owner_user_id ON public.assistants USING btree (owner_user_id);


--
-- Name: idx_assistants_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assistants_updated_at ON public.assistants USING btree (updated_at DESC);


--
-- Name: idx_chat_file_uploads_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_file_uploads_chat_id ON public.chat_file_uploads USING btree (chat_id);


--
-- Name: idx_chat_file_uploads_file_upload_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_file_uploads_file_upload_id ON public.chat_file_uploads USING btree (file_upload_id);


--
-- Name: idx_chats_assistant_configuration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_assistant_configuration ON public.chats USING btree (((assistant_configuration ->> 'assistant_id'::text)));


--
-- Name: idx_chats_delegated_runs; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_delegated_runs ON public.chats USING btree (owner_user_id, updated_at DESC) WHERE ((assistant_configuration #>> '{provenance,kind}'::text[]) = 'delegation'::text);


--
-- Name: idx_chats_origin_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_origin_chat_id ON public.chats USING btree (origin_chat_id) WHERE (origin_chat_id IS NOT NULL);


--
-- Name: idx_chats_owner_user_id_is_pinned; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_owner_user_id_is_pinned ON public.chats USING btree (owner_user_id, is_pinned);


--
-- Name: idx_chats_resolved_title_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chats_resolved_title_search ON public.chats USING gin (to_tsvector('simple'::regconfig, COALESCE(NULLIF(btrim(title_by_user_provided), ''::text), NULLIF(btrim(title_by_summary), ''::text), 'Untitled Chat'::text)));


--
-- Name: idx_file_uploads_owner_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_uploads_owner_user_id ON public.file_uploads USING btree (owner_user_id);


--
-- Name: idx_message_feedbacks_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_feedbacks_created_at ON public.message_feedbacks USING btree (created_at DESC);


--
-- Name: idx_message_feedbacks_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_feedbacks_message_id ON public.message_feedbacks USING btree (message_id);


--
-- Name: idx_messages_active_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_active_thread ON public.messages USING btree (is_message_in_active_thread) WHERE (is_message_in_active_thread = true);


--
-- Name: idx_messages_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_chat_id ON public.messages USING btree (chat_id);


--
-- Name: idx_messages_previous_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_previous_message_id ON public.messages USING btree (previous_message_id);


--
-- Name: idx_messages_sibling_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_sibling_message_id ON public.messages USING btree (sibling_message_id);


--
-- Name: idx_share_grants_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_created_at ON public.share_grants USING btree (created_at DESC);


--
-- Name: idx_share_grants_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_resource ON public.share_grants USING btree (resource_type, resource_id);


--
-- Name: idx_share_grants_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_grants_subject ON public.share_grants USING btree (subject_type, subject_id_type, subject_id);


--
-- Name: idx_share_links_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_links_enabled ON public.share_links USING btree (enabled);


--
-- Name: idx_share_links_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_links_resource ON public.share_links USING btree (resource_type, resource_id);


--
-- Name: idx_users_issuer_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_issuer_subject ON public.users USING btree (issuer, subject);


--
-- Name: runtime_configuration_source_service_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX runtime_configuration_source_service_idx ON public.runtime_configuration USING btree (source_service);


--
-- Name: temp_chat_generation_commands_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX temp_chat_generation_commands_pending_idx ON public.temp_chat_generation_commands USING btree (generation_id, command_id) WHERE (consumed_at IS NULL);


--
-- Name: temp_chat_generation_events_generation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX temp_chat_generation_events_generation_idx ON public.temp_chat_generation_events USING btree (generation_id, event_id);


--
-- Name: temp_chat_generations_heartbeat_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX temp_chat_generations_heartbeat_idx ON public.temp_chat_generations USING btree (heartbeat_at) WHERE (state = 'running'::text);


--
-- Name: messages ensure_single_active_message_in_thread; Type: TRIGGER; Schema: public; Owner: -
--

CREATE CONSTRAINT TRIGGER ensure_single_active_message_in_thread AFTER INSERT OR UPDATE ON public.messages DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.check_active_thread_siblings_constraint();


--
-- Name: chats on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.chats FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: file_uploads on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: messages on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: users on_update_set_updated_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_file_uploads on_update_set_updated_columns_assistant_file_uploads; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistant_file_uploads BEFORE UPDATE ON public.assistant_file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_hub_assistant_versions on_update_set_updated_columns_assistant_hub_assistant_versions; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistant_hub_assistant_versions BEFORE UPDATE ON public.assistant_hub_assistant_versions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_hub_assistants on_update_set_updated_columns_assistant_hub_assistants; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistant_hub_assistants BEFORE UPDATE ON public.assistant_hub_assistants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_hub_reviews on_update_set_updated_columns_assistant_hub_reviews; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistant_hub_reviews BEFORE UPDATE ON public.assistant_hub_reviews FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistants on_update_set_updated_columns_assistants; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_assistants BEFORE UPDATE ON public.assistants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: chat_file_uploads on_update_set_updated_columns_chat_file_uploads; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_chat_file_uploads BEFORE UPDATE ON public.chat_file_uploads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: mcp_server_oauth_authorization_states on_update_set_updated_columns_mcp_server_oauth_authorization_st; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_mcp_server_oauth_authorization_st BEFORE UPDATE ON public.mcp_server_oauth_authorization_states FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: mcp_server_oauth_clients on_update_set_updated_columns_mcp_server_oauth_clients; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_mcp_server_oauth_clients BEFORE UPDATE ON public.mcp_server_oauth_clients FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: mcp_server_oauth_credentials on_update_set_updated_columns_mcp_server_oauth_credentials; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_mcp_server_oauth_credentials BEFORE UPDATE ON public.mcp_server_oauth_credentials FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: message_feedbacks on_update_set_updated_columns_message_feedbacks; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_message_feedbacks BEFORE UPDATE ON public.message_feedbacks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: runtime_configuration on_update_set_updated_columns_runtime_configuration; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_runtime_configuration BEFORE UPDATE ON public.runtime_configuration FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: share_grants on_update_set_updated_columns_share_grants; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_share_grants BEFORE UPDATE ON public.share_grants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: share_links on_update_set_updated_columns_share_links; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_share_links BEFORE UPDATE ON public.share_links FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: user_tool_approval_settings on_update_set_updated_columns_user_tool_approval_settings; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER on_update_set_updated_columns_user_tool_approval_settings BEFORE UPDATE ON public.user_tool_approval_settings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: user_preferences set_updated_at_column; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at_column BEFORE UPDATE ON public.user_preferences FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: assistant_file_uploads assistant_file_uploads_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_file_uploads assistant_file_uploads_file_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_file_uploads
    ADD CONSTRAINT assistant_file_uploads_file_upload_id_fkey FOREIGN KEY (file_upload_id) REFERENCES public.file_uploads(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_assistant_versions assistant_hub_assistant_versions_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistant_versions
    ADD CONSTRAINT assistant_hub_assistant_versions_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_assistant_versions assistant_hub_assistant_versions_hub_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistant_versions
    ADD CONSTRAINT assistant_hub_assistant_versions_hub_assistant_id_fkey FOREIGN KEY (assistant_hub_assistant_id) REFERENCES public.assistant_hub_assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_assistants assistant_hub_assistants_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistants
    ADD CONSTRAINT assistant_hub_assistants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_assistants assistant_hub_assistants_source_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_assistants
    ADD CONSTRAINT assistant_hub_assistants_source_assistant_id_fkey FOREIGN KEY (source_assistant_id) REFERENCES public.assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_reviews assistant_hub_reviews_hub_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_reviews
    ADD CONSTRAINT assistant_hub_reviews_hub_assistant_id_fkey FOREIGN KEY (assistant_hub_assistant_id) REFERENCES public.assistant_hub_assistants(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_reviews assistant_hub_reviews_reviewer_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_reviews
    ADD CONSTRAINT assistant_hub_reviews_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: assistant_hub_reviews assistant_hub_reviews_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistant_hub_reviews
    ADD CONSTRAINT assistant_hub_reviews_version_id_fkey FOREIGN KEY (assistant_hub_assistant_version_id) REFERENCES public.assistant_hub_assistant_versions(id) ON DELETE CASCADE;


--
-- Name: assistants assistants_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assistants
    ADD CONSTRAINT assistants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: chat_file_uploads chat_file_uploads_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: chat_file_uploads chat_file_uploads_file_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_file_uploads
    ADD CONSTRAINT chat_file_uploads_file_upload_id_fkey FOREIGN KEY (file_upload_id) REFERENCES public.file_uploads(id) ON DELETE CASCADE;


--
-- Name: chats chats_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_assistant_id_fkey FOREIGN KEY (assistant_id) REFERENCES public.assistants(id);


--
-- Name: mcp_server_oauth_authorization_states mcp_server_oauth_authorization_states_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_server_oauth_authorization_states
    ADD CONSTRAINT mcp_server_oauth_authorization_states_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: mcp_server_oauth_credentials mcp_server_oauth_credentials_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_server_oauth_credentials
    ADD CONSTRAINT mcp_server_oauth_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: message_feedbacks message_feedbacks_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_feedbacks
    ADD CONSTRAINT message_feedbacks_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: messages messages_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id);


--
-- Name: messages messages_previous_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_previous_message_id_fkey FOREIGN KEY (previous_message_id) REFERENCES public.messages(id);


--
-- Name: messages messages_sibling_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_sibling_message_id_fkey FOREIGN KEY (sibling_message_id) REFERENCES public.messages(id);


--
-- Name: temp_chat_generation_commands temp_chat_generation_commands_generation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generation_commands
    ADD CONSTRAINT temp_chat_generation_commands_generation_id_fkey FOREIGN KEY (generation_id) REFERENCES public.temp_chat_generations(generation_id) ON DELETE CASCADE;


--
-- Name: temp_chat_generation_events temp_chat_generation_events_generation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generation_events
    ADD CONSTRAINT temp_chat_generation_events_generation_id_fkey FOREIGN KEY (generation_id) REFERENCES public.temp_chat_generations(generation_id) ON DELETE CASCADE;


--
-- Name: temp_chat_generations temp_chat_generations_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temp_chat_generations
    ADD CONSTRAINT temp_chat_generations_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: user_preferences user_preferences_starting_hub_assistant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_starting_hub_assistant_id_fkey FOREIGN KEY (starting_hub_assistant_id) REFERENCES public.assistant_hub_assistants(id) ON DELETE SET NULL;


--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_tool_approval_settings user_tool_approval_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tool_approval_settings
    ADD CONSTRAINT user_tool_approval_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict OM7cNXdBdyBvLZvgpYZtJmnVfBbiARdfWSfbAR86ERODzDTyXhtRLbkmz7CSgJk

