//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assistant_hub_assistants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub source_assistant_id: Uuid,
    pub owner_user_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub featured: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assistant_hub_assistant_versions::Entity")]
    AssistantHubAssistantVersions,
    #[sea_orm(has_many = "super::assistant_hub_reviews::Entity")]
    AssistantHubReviews,
    #[sea_orm(
        belongs_to = "super::assistants::Entity",
        from = "Column::SourceAssistantId",
        to = "super::assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Assistants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::assistant_hub_assistant_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubAssistantVersions.def()
    }
}

impl Related<super::assistant_hub_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubReviews.def()
    }
}

impl Related<super::assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assistants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
