//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assistant_hub_reviews")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub assistant_hub_assistant_id: Uuid,
    pub assistant_hub_assistant_version_id: Uuid,
    pub reviewer_user_id: Uuid,
    pub score: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assistant_hub_assistant_versions::Entity",
        from = "Column::AssistantHubAssistantVersionId",
        to = "super::assistant_hub_assistant_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AssistantHubAssistantVersions,
    #[sea_orm(
        belongs_to = "super::assistant_hub_assistants::Entity",
        from = "Column::AssistantHubAssistantId",
        to = "super::assistant_hub_assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AssistantHubAssistants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ReviewerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::assistant_hub_assistant_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubAssistantVersions.def()
    }
}

impl Related<super::assistant_hub_assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubAssistants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
