//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assistant_store_assistant_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub assistant_store_assistant_id: Uuid,
    pub assistant_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub is_published: bool,
    pub is_current_published_version: bool,
    #[sea_orm(column_type = "Text")]
    pub version_number: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version_comment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub creator_review_comment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reviewer_review_comment: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub long_description: String,
    pub category_ids: Option<Vec<String>>,
    pub keywords: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary")]
    pub diff_summary: Json,
    pub submitted_at: DateTimeWithTimeZone,
    pub reviewed_at: Option<DateTimeWithTimeZone>,
    pub withdrawn_at: Option<DateTimeWithTimeZone>,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assistants::Entity",
        from = "Column::AssistantId",
        to = "super::assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Assistants,
    #[sea_orm(
        belongs_to = "super::assistant_store_assistants::Entity",
        from = "Column::AssistantStoreAssistantId",
        to = "super::assistant_store_assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AssistantStoreAssistants,
}

impl Related<super::assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assistants.def()
    }
}

impl Related<super::assistant_store_assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantStoreAssistants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
