//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub issuer: String,
    #[sea_orm(column_type = "Text")]
    pub subject: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assistant_hub_assistants::Entity")]
    AssistantHubAssistants,
    #[sea_orm(has_many = "super::assistants::Entity")]
    Assistants,
    #[sea_orm(has_many = "super::mcp_server_oauth_authorization_states::Entity")]
    McpServerOauthAuthorizationStates,
    #[sea_orm(has_many = "super::mcp_server_oauth_credentials::Entity")]
    McpServerOauthCredentials,
    #[sea_orm(has_one = "super::user_preferences::Entity")]
    UserPreferences,
}

impl Related<super::assistant_hub_assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubAssistants.def()
    }
}

impl Related<super::assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assistants.def()
    }
}

impl Related<super::mcp_server_oauth_authorization_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::McpServerOauthAuthorizationStates.def()
    }
}

impl Related<super::mcp_server_oauth_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::McpServerOauthCredentials.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
