//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_preferences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub nickname: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub job_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub assistant_custom_instructions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub assistant_additional_information: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_chat_provider: Option<String>,
    pub starting_hub_assistant_id: Option<Uuid>,
    pub starting_assistant_id: Option<Uuid>,
    pub starting_assistant_cleared: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assistant_hub_assistants::Entity",
        from = "Column::StartingHubAssistantId",
        to = "super::assistant_hub_assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AssistantHubAssistants,
    #[sea_orm(
        belongs_to = "super::assistants::Entity",
        from = "Column::StartingAssistantId",
        to = "super::assistants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Assistants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::assistant_hub_assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantHubAssistants.def()
    }
}

impl Related<super::assistants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assistants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
