#requires -Version 7.2
<#
.SYNOPSIS
Checks and configures the Azure side of the Erato Teams bot. Version 1.1.1.
.DESCRIPTION
Run in Azure Cloud Shell (PowerShell), or PowerShell 7.2+ with Azure CLI.
The default run only reads Azure and Entra. -WhatIf previews changes.
-Apply shows the plan and requests confirmation before it:
creates the single-tenant Azure Bot for the existing app registration when
-ResourceGroup and -BotName name one that does not exist yet (registering the
Microsoft.BotService provider if needed), sets its messaging endpoint and Teams
channel, adds SSO settings to the existing authentication app, creates a
separate OAuth connection with a dedicated credential (or repairs the
authentication-app-ID URI generated by version 1.0.0), and grants tenant-wide
consent for the delegated Graph permissions unless -SkipConsent is set.
Existing redirects, permissions, credentials and bot identity are preserved.
Erato itself and the Teams package upload remain separate.
Public Azure and the global Bot Framework token service are supported.
Exit codes: 0 = checks/writes completed; 1 = settings missing; 2 = blocked/failed.
Source and instructions: https://erato.chat/docs/integrations/ms_teams
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory)][guid]$TenantId,
    [Parameter(Mandatory)][guid]$SubscriptionId,
    [Parameter(Mandatory)][guid]$BotAppId,
    [Parameter(Mandatory)][guid]$AuthAppId,
    [Parameter(Mandatory)][string]$BaseUrl,
    [string]$MessagingEndpoint,
    [string]$SsoResource,
    [ValidatePattern('^[A-Za-z0-9_-]{1,64}$')][string]$CurrentConnection = 'graph',
    [ValidatePattern('^[A-Za-z0-9_-]{1,64}$')][string]$ConnectionName = 'graph-sso',
    [string]$ResourceGroup,
    [string]$BotName,
    [switch]$SkipConsent,
    [switch]$Apply,
    [switch]$Json
)

$ErrorActionPreference = 'Stop'
$script:GraphAppId = '00000003-0000-0000-c000-000000000000'
$script:ProviderId = '30dd229c-58e3-4a48-bdfd-91ec48eb906c'
$script:TeamsClients = @('1fec8e78-bce4-4aaf-ab1b-5451cc387264', '5e3ce6c0-2b1f-4285-8d4b-75ee78787346')
$script:Scopes = @('openid', 'profile', 'email', 'offline_access', 'User.Read', 'GroupMember.Read.All', 'Files.Read.All', 'Sites.Read.All', 'Chat.Read', 'ChannelMessage.Read.All')
$script:Callback = 'https://token.botframework.com/.auth/web/redirect'
$script:MessagesPath = '/api/integrations/ms_teams/messages'
$script:BotApiVersion = '2022-09-15'
$script:ConnectionQuery = "{name:name,properties:{clientId:properties.clientId,scopes:properties.scopes,serviceProviderId:properties.serviceProviderId,parameters:properties.parameters[?key=='tenantId' || key=='tokenExchangeUrl']}}"

<#
.SYNOPSIS
Runs Azure CLI and parses its JSON response, withholding raw errors that may contain secrets.
#>
function Invoke-EratoAz {
    param([string[]]$Arguments)
    # Capture both streams. Raw CLI errors can contain request bodies/secrets.
    $output = & az @Arguments --only-show-errors --output json 2>&1
    $code = $LASTEXITCODE
    $text = ($output | ForEach-Object { "$_" }) -join "`n"
    if ($code -ne 0) {
        $reason = switch -Regex ($text) {
            'ResourceNotFound|Request_ResourceNotFound|\b404\b' { 'NotFound'; break }
            'Forbidden|AuthorizationFailed|Insufficient privileges|\b403\b' { 'AccessDenied'; break }
            'az login|AADSTS|expired|\b401\b' { 'SignInRequired'; break }
            default { 'RequestFailed' }
        }
        $context = $(if ($script:Step) { " while $script:Step" } else { '' })
        throw "Azure request failed$context ($reason). Check the selected account and permissions; raw responses are withheld."
    }
    if ($text.Trim()) {
        try { return ConvertFrom-Json -InputObject $text -AsHashtable }
        catch { throw 'Azure CLI returned an unexpected response; raw output is withheld.' }
    }
    return @{}
}

<#
.SYNOPSIS
Calls public Azure or Microsoft Graph through Azure CLI.
.DESCRIPTION
Sends JSON bodies through a private temporary file instead of process arguments,
then removes it even if the request fails. Optional Query filters the CLI response.
#>
function Invoke-EratoApi {
    param([string]$Url, [string]$Method = 'GET', [hashtable]$Body, [string]$Query)
    if ($Url -cnotmatch '^https://(graph\.microsoft\.com/v1\.0/|management\.azure\.com/)') {
        throw 'Refusing a request outside public Azure and Microsoft Graph.'
    }
    $arguments = @('rest', '--method', $Method, '--url', $Url)
    if ($Query) { $arguments += @('--query', $Query) }
    $directory = $null
    try {
        if ($Body) {
            # Never put a credential in process arguments. Restrict the temporary
            # directory BEFORE writing the body, and remove it in finally.
            $directory = Join-Path ([IO.Path]::GetTempPath()) ('erato-teams-' + [guid]::NewGuid())
            [IO.Directory]::CreateDirectory($directory) | Out-Null
            if ($IsWindows) {
                $acl = Get-Acl $directory
                $acl.SetAccessRuleProtection($true, $false)
                $identity = [Security.Principal.WindowsIdentity]::GetCurrent().Name
                $rule = [Security.AccessControl.FileSystemAccessRule]::new($identity, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
                $acl.AddAccessRule($rule)
                Set-Acl -Path $directory -AclObject $acl
            } else {
                & chmod 700 $directory
                if ($LASTEXITCODE -ne 0) { throw 'Could not secure the temporary request directory.' }
            }
            $file = Join-Path $directory 'request.json'
            [IO.File]::WriteAllText($file, ($Body | ConvertTo-Json -Depth 50 -Compress))
            $arguments += @('--headers', 'Content-Type=application/json', '--body', "@$file")
        }
        return Invoke-EratoAz -Arguments $arguments
    } finally {
        if ($directory) { [IO.Directory]::Delete($directory, $true) }
    }
}

<#
.SYNOPSIS
Collects all pages of an Azure or Graph response, rejecting invalid or excessive pagination.
#>
function Get-EratoCollection {
    param([string]$Url)
    $items = @()
    for ($page = 0; $page -lt 100; $page++) {
        $response = Invoke-EratoApi -Url $Url
        if (-not $response.ContainsKey('value')) { throw 'Azure returned an invalid collection.' }
        $items += @($response.value)
        $Url = $response.'@odata.nextLink'
        if (-not $Url) { $Url = $response.nextLink }
        if (-not $Url) { return ,$items }
    }
    throw 'Azure returned too many pages; narrow the selected resource.'
}

<#
.SYNOPSIS
Appends a PASS or MISSING check to the report; missing checks determine its exit code.
#>
function Add-EratoCheck {
    param($Checks, [string]$Name, [bool]$Pass, [string]$Detail)
    $Checks.Add(@{ name = $Name; status = $(if ($Pass) { 'PASS' } else { 'MISSING' }); detail = $Detail })
}

<#
.SYNOPSIS
Appends informational context to the report without affecting its exit code.
#>
function Add-EratoInfo {
    param($Checks, [string]$Name, [string]$Detail)
    $Checks.Add(@{ name = $Name; status = 'INFO'; detail = $Detail })
}

<#
.SYNOPSIS
Reads the app's effective client-secret and identifier-URI policy restrictions.
.DESCRIPTION
App-specific rules take precedence over tenant defaults. Returns whether policies
were readable, whether secrets are blocked, their maximum lifetime, and URI limits.
Reading requires Policy.Read.All. If access is denied, Apply can still run;
Entra enforces the restrictions.
#>
function Get-EratoPolicyLimits {
    param($App)
    $script:Step = 'reading app management policies'
    try {
        $appPolicies = @(Get-EratoCollection -Url "https://graph.microsoft.com/v1.0/applications/$($App.id)/appManagementPolicies")
        $tenant = Invoke-EratoApi -Url 'https://graph.microsoft.com/v1.0/policies/defaultAppManagementPolicy'
    } catch {
        if ($_.Exception.Message -match '\(AccessDenied\)') { return @{ readable = $false } }
        throw
    }
    $created = $(if ($App.createdDateTime) { [DateTime]$App.createdDateTime } else { [DateTime]::MaxValue })
    $applies = {
        param($restriction)
        $restriction -and $restriction.state -ne 'disabled' -and
        (-not $restriction.restrictForAppsCreatedAfterDateTime -or [DateTime]$restriction.restrictForAppsCreatedAfterDateTime -le $created)
    }
    $appPolicy = @($appPolicies | Where-Object { $_.isEnabled }) | Select-Object -First 1
    # An app-specific policy takes precedence over the tenant default.
    $passwordRules = $(if ($appPolicy -and $appPolicy.restrictions.passwordCredentials) { $appPolicy.restrictions.passwordCredentials }
        elseif ($tenant.isEnabled) { $tenant.applicationRestrictions.passwordCredentials })
    $passwords = @($passwordRules | Where-Object { & $applies $_ })
    $maxDays = $null
    foreach ($rule in @($passwords | Where-Object { $_.restrictionType -eq 'passwordLifetime' -and $_.maxLifetime })) {
        try { $days = [int][Math]::Floor([System.Xml.XmlConvert]::ToTimeSpan("$($rule.maxLifetime)").TotalDays) } catch { continue }
        if ($null -eq $maxDays -or $days -lt $maxDays) { $maxDays = $days }
    }
    $uriRules = $(if ($appPolicy -and $appPolicy.restrictions.identifierUris) { $appPolicy.restrictions.identifierUris }
        elseif ($tenant.isEnabled) { $tenant.applicationRestrictions.identifierUris })
    $uriLimits = @(@($uriRules.nonDefaultUriAddition, $uriRules.uriAdditionWithoutUniqueTenantIdentifier) | Where-Object { & $applies $_ })
    return @{ readable = $true
        blockSecrets = [bool]@($passwords | Where-Object { $_.restrictionType -eq 'passwordAddition' }).Count
        maxSecretDays = $maxDays
        uriRestrictedForV2 = [bool]@($uriLimits | Where-Object { -not $_.excludeAppsReceivingV2Tokens }).Count
        uriNeedsV2 = [bool]@($uriLimits | Where-Object { $_.excludeAppsReceivingV2Tokens }).Count }
}

<#
.SYNOPSIS
Checks the OAuth connection's app, tenant, provider, SSO resource and required scopes.
#>
function Test-EratoConnection {
    param($Connection, $Settings)
    if (-not $Connection) { return $false }
    $p = $Connection.properties
    $parameters = @{}
    foreach ($item in $p.parameters) { $parameters[$item.key] = $item.value }
    return ($p.clientId -eq $Settings.AuthAppId -and $p.serviceProviderId -eq $script:ProviderId -and
        $parameters.tenantId -eq $Settings.TenantId -and $parameters.tokenExchangeUrl -ceq $Settings.SsoResource -and
        @($script:Scopes | Where-Object { $_ -cnotin ($p.scopes -split '\s+') }).Count -eq 0)
}

<#
.SYNOPSIS
Detects the version 1.0.0 resource-URI bug when all other connection settings match.
#>
function Test-EratoLegacyResourceConnection {
    param($Connection, $Settings)
    if (-not $Connection -or $Settings.AuthAppId -eq $Settings.BotAppId) { return $false }
    # Only repair the old helper's ID substitution. Every other connection
    # setting must already match; unrelated connections remain untouched.
    $legacy = $Settings.Clone()
    $legacy.SsoResource = $Settings.SsoResource.Substring(0, $Settings.SsoResource.Length - $Settings.BotAppId.Length) + $Settings.AuthAppId
    return Test-EratoConnection $Connection $legacy
}

<#
.SYNOPSIS
Reads Azure and Entra state and checks it against the requested Teams bot settings.
.DESCRIPTION
Makes no cloud changes. Returns a public Report with checks and remaining steps,
plus the app, bot, connection, policy limits and consent state needed to plan changes.
Missing settings set Report.exitCode to 1; unrecoverable read errors throw.
#>
function Get-EratoAudit {
    param([hashtable]$Settings)
    $script:Step = 'checking the Azure CLI sign-in'
    $account = Invoke-EratoAz -Arguments @('account', 'show', '--query', '{tenantId:tenantId,id:id,environmentName:environmentName}')
    $target = Invoke-EratoAz -Arguments @('account', 'show', '--subscription', $Settings.SubscriptionId, '--query', '{tenantId:tenantId,id:id,environmentName:environmentName}')
    if ($account.environmentName -ne 'AzureCloud' -or $target.environmentName -ne 'AzureCloud') { throw 'Select a public Azure subscription.' }
    if ($account.tenantId -ne $Settings.TenantId -or $target.tenantId -ne $Settings.TenantId) {
        throw "Wrong Azure CLI tenant. Run az login --tenant $($Settings.TenantId), then rerun the check. No cloud changes were made."
    }
    $subscriptionUrl = "https://management.azure.com/subscriptions/$($Settings.SubscriptionId)"
    $bot = $null; $providerRegistered = $true
    $script:Step = 'reading the Azure Bot'
    if ($Settings.ResourceGroup -and $Settings.BotName) {
        # Resource-scoped administrators need not enumerate the subscription.
        $group = [uri]::EscapeDataString($Settings.ResourceGroup)
        $name = [uri]::EscapeDataString($Settings.BotName)
        $botId = "/subscriptions/$($Settings.SubscriptionId)/resourceGroups/$group/providers/Microsoft.BotService/botServices/$name"
        try { $bot = Invoke-EratoApi -Url "https://management.azure.com$botId`?api-version=$script:BotApiVersion" }
        catch { if ($_.Exception.Message -notmatch '\(NotFound\)') { throw } }
        if ($bot -and $bot.properties.msaAppId -ne $Settings.BotAppId) { throw "Azure Bot '$($Settings.BotName)' belongs to another app registration. Choose another bot name; it will not be changed." }
        if (-not $bot) {
            # Creating a bot needs an existing resource group and the provider.
            try { Invoke-EratoApi -Url "$subscriptionUrl/resourcegroups/$group`?api-version=2021-04-01" | Out-Null }
            catch {
                if ($_.Exception.Message -match '\(NotFound\)') { throw "Resource group '$($Settings.ResourceGroup)' does not exist. Create it (az group create) or choose an existing one. No cloud changes were made." }
                throw
            }
            $provider = Invoke-EratoApi -Url "$subscriptionUrl/providers/Microsoft.BotService?api-version=2021-04-01"
            $providerRegistered = $provider.registrationState -eq 'Registered'
        }
    } else {
        $bots = Get-EratoCollection -Url "$subscriptionUrl/providers/Microsoft.BotService/botServices?api-version=$script:BotApiVersion"
        $matches = @($bots | Where-Object { $_.properties.msaAppId -eq $Settings.BotAppId })
        if ($matches.Count -eq 0) { throw "No Azure Bot in the selected subscription uses app $($Settings.BotAppId). To create one, enter a resource group and bot name on the Erato setup page and copy the command again (or pass -ResourceGroup and -BotName). No cloud changes were made." }
        if ($matches.Count -ne 1) { throw "Found $($matches.Count) matching bots in the selected subscription. Enter the resource group and bot name of the one to use on the Erato setup page and copy the command again (or pass -ResourceGroup and -BotName)." }
        $bot = $matches[0]
        $botId = $bot.id
    }
    if ($bot -and $bot.id -notmatch "^/subscriptions/$([regex]::Escape($Settings.SubscriptionId))/resourceGroups/[^/]+/providers/Microsoft.BotService/botServices/[^/]+$") { throw 'Unexpected bot resource identity.' }
    $checks = [Collections.Generic.List[object]]::new()
    if ($bot) {
        Add-EratoCheck $checks 'Bot tenant' ($bot.properties.msaAppTenantId -eq $Settings.TenantId) $Settings.TenantId
        Add-EratoCheck $checks 'Single-tenant bot' ($bot.properties.msaAppType -eq 'SingleTenant') 'Existing single-tenant bot required'
        Add-EratoCheck $checks 'Messaging endpoint' ($bot.properties.endpoint -ceq $Settings.MessagingEndpoint) $Settings.MessagingEndpoint
        Add-EratoCheck $checks 'Teams channel' ('msteams' -in $bot.properties.enabledChannels) 'Microsoft Teams channel enabled'
    } else {
        Add-EratoCheck $checks 'Azure Bot' $false "Apply creates '$($Settings.BotName)' in resource group '$($Settings.ResourceGroup)'"
        if (-not $providerRegistered) { Add-EratoCheck $checks 'Bot Service provider' $false 'Apply registers Microsoft.BotService in the subscription' }
    }
    $script:Step = 'reading the Entra app registration'
    $appSelect = 'id,appId,displayName,signInAudience,createdDateTime,identifierUris,api,web,spa,requiredResourceAccess'
    $app = Invoke-EratoApi -Url "https://graph.microsoft.com/v1.0/applications(appId='$($Settings.AuthAppId)')?`$select=$appSelect"
    Add-EratoCheck $checks 'Single-tenant authentication app' ($app.signInAudience -eq 'AzureADMyOrg') $Settings.AuthAppId
    $limits = Get-EratoPolicyLimits $app
    $script:Step = 'reading Microsoft Graph permissions'
    $graphFilter = [uri]::EscapeDataString("appId eq '$script:GraphAppId'")
    $graph = @(Get-EratoCollection -Url "https://graph.microsoft.com/v1.0/servicePrincipals?`$filter=$graphFilter&`$select=id,oauth2PermissionScopes")
    if ($graph.Count -ne 1) { throw 'Could not uniquely resolve Microsoft Graph permissions.' }
    $scopeIds = @{}
    foreach ($scope in $graph[0].oauth2PermissionScopes) { if ($scope.isEnabled) { $scopeIds[$scope.value] = $scope.id } }
    foreach ($name in $script:Scopes) { if (-not $scopeIds[$name]) { throw "Microsoft Graph permission unavailable: $name" } }
    Add-EratoCheck $checks 'Application ID URI' ($Settings.SsoResource -cin $app.identifierUris) $Settings.SsoResource
    Add-EratoCheck $checks 'V2 access tokens' ($app.api.requestedAccessTokenVersion -eq 2) 'Access tokens for the exposed API'
    $scope = @($app.api.oauth2PermissionScopes | Where-Object { $_.value -ceq 'access_as_user' -and $_.isEnabled })
    Add-EratoCheck $checks 'access_as_user scope' ($scope.Count -eq 1) 'Enabled delegated scope'
    foreach ($client in $script:TeamsClients) {
        $authorized = @($app.api.preAuthorizedApplications | Where-Object { $_.appId -eq $client })
        Add-EratoCheck $checks "Teams client $client" ($scope.Count -eq 1 -and $scope[0].id -in $authorized.delegatedPermissionIds) 'Pre-authorized for access_as_user'
    }
    Add-EratoCheck $checks 'OAuth web callback' ($script:Callback -cin $app.web.redirectUris) $script:Callback
    $requested = @($app.requiredResourceAccess | Where-Object { $_.resourceAppId -eq $script:GraphAppId }).resourceAccess
    $missing = @($script:Scopes | Where-Object { $scopeIds[$_] -notin @($requested | Where-Object { $_.type -eq 'Scope' }).id })
    Add-EratoCheck $checks 'Delegated Graph permissions' ($missing.Count -eq 0) $(if ($missing) { 'Missing: ' + ($missing -join ', ') } else { 'All requested permissions present' })
    $script:Step = 'reading admin consent'
    $appFilter = [uri]::EscapeDataString("appId eq '$($Settings.AuthAppId)'")
    $principals = @(Get-EratoCollection -Url "https://graph.microsoft.com/v1.0/servicePrincipals?`$filter=$appFilter&`$select=id")
    $granted = @(); $grant = $null
    if ($principals.Count -eq 1) {
        $filter = [uri]::EscapeDataString("clientId eq '$($principals[0].id)'")
        $grants = Get-EratoCollection -Url "https://graph.microsoft.com/v1.0/oauth2PermissionGrants?`$filter=$filter&`$select=id,consentType,resourceId,scope"
        $grant = @($grants | Where-Object { $_.consentType -eq 'AllPrincipals' -and $_.resourceId -eq $graph[0].id }) | Select-Object -First 1
        if ($grant) { $granted = @($grant.scope -split '\s+') }
    }
    $missingConsent = @($script:Scopes | Where-Object { $_ -cnotin $granted })
    Add-EratoCheck $checks 'Tenant admin consent' ($missingConsent.Count -eq 0) $(if ($missingConsent) { 'Missing consent for: ' + ($missingConsent -join ', ') } else { 'Required delegated scopes granted' })
    $connection = $null
    $script:Step = 'reading the OAuth connection'
    $connectionUrl = "https://management.azure.com$botId/connections/$($Settings.ConnectionName)?api-version=$script:BotApiVersion"
    if ($bot) {
        try { $connection = Invoke-EratoApi -Url $connectionUrl -Query $script:ConnectionQuery }
        catch { if ($_.Exception.Message -notmatch '\(NotFound\)') { throw } }
    }
    Add-EratoCheck $checks 'SSO OAuth connection' (Test-EratoConnection $connection $Settings) $Settings.ConnectionName
    $secretDays = 365
    if (-not $limits.readable) {
        Add-EratoInfo $checks 'App management policies' 'Not readable with this account (needs Policy.Read.All). Entra still enforces them when Apply runs.'
    } else {
        if ($limits.maxSecretDays -and $limits.maxSecretDays -lt $secretDays) {
            $secretDays = [Math]::Max(1, $limits.maxSecretDays - 1)
            Add-EratoInfo $checks 'Secret lifetime policy' "Capped at $($limits.maxSecretDays) days; the OAuth credential gets $secretDays days."
        }
        if (-not $connection) {
            Add-EratoCheck $checks 'Client secrets allowed' (-not $limits.blockSecrets) $(if ($limits.blockSecrets) { 'An app management policy blocks new client secrets on this app; the OAuth connection needs one. Ask an administrator for an exemption.' } else { 'The OAuth connection can get its credential' })
        }
        if ($Settings.SsoResource -cnotin $app.identifierUris) {
            if ($limits.uriRestrictedForV2) {
                Add-EratoInfo $checks 'Identifier URI policy' "An app management policy restricts new Application ID URIs. $($Settings.SsoResource) is only accepted on a verified domain of the tenant or with an exemption."
            } elseif ($limits.uriNeedsV2) {
                Add-EratoInfo $checks 'Identifier URI policy' 'Entra accepts the Application ID URI once the app issues v2 access tokens; Apply enables them first.'
            }
        }
    }
    $consentUrl = "https://login.microsoftonline.com/$($Settings.TenantId)/adminconsent?client_id=$($Settings.AuthAppId)"
    $steps = @()
    if ($missingConsent) { $steps += "Have an administrator grant tenant-wide consent: $consentUrl" }
    $steps += @(
        "Optional: use Test Connection on OAuth connection '$($Settings.ConnectionName)' in Azure Bot Configuration.",
        'Download the Teams package from the Erato setup page. In Microsoft 365 admin center, Settings, Integrated apps, upload it as a Teams app (or update the existing Erato app) and deploy it to its users: deployed apps are installed and updated without asking them. Alternatively, upload it in Teams admin center and install it with an app setup policy.',
        'Send the bot a message in Teams; the setup page shows when Erato receives it. Then test the tab and the other Office add-ins.'
    )
    # Only these public fields go into the printed/JSON report.
    $report = [ordered]@{
        version = '1.1.1'; checkedAt = [DateTime]::UtcNow.ToString('o'); mode = 'Check'
        tenantId = $Settings.TenantId; subscriptionId = $Settings.SubscriptionId
        botName = $(if ($bot) { $bot.name } else { $Settings.BotName }); botAppId = $Settings.BotAppId; authAppId = $Settings.AuthAppId
        baseUrl = $Settings.BaseUrl; messagingEndpoint = $Settings.MessagingEndpoint; connectionName = $Settings.ConnectionName
        checks = $checks.ToArray(); changes = @(); remainingSteps = $steps
        note = 'Azure checks do not verify the bot route, installed Teams package, credential validity, or end-to-end sign-in.'
        exitCode = $(if (@($checks | Where-Object status -eq 'MISSING').Count) { 1 } else { 0 })
    }
    return @{ Report = $report; App = $app; Bot = $bot; BotId = $botId; ProviderRegistered = $providerRegistered; Connection = $connection; ConnectionUrl = $connectionUrl
        SecretDays = $secretDays; BlockSecrets = [bool]$limits.blockSecrets
        ScopeIds = $scopeIds; GraphPrincipalId = $graph[0].id; AuthPrincipalId = $(if ($principals.Count -eq 1) { $principals[0].id }); Grant = $grant; MissingConsent = $missingConsent; ConsentUrl = $consentUrl }
}

<#
.SYNOPSIS
Builds an additive setup plan from the audit without writing to Azure or Entra.
.DESCRIPTION
Preserves existing app settings and rejects incompatible identities or connections.
Returns the application patch and bot, connection and consent actions for preview
or Apply, including the allowed credential lifetime and legacy URI repair.
#>
function New-EratoSsoPlan {
    param($Audit, $Settings)
    # A bot in another tenant or of another type cannot be adjusted in place;
    # its endpoint and Teams channel can.
    $basics = @('Bot tenant', 'Single-tenant bot', 'Single-tenant authentication app')
    if (@($Audit.Report.checks | Where-Object { $_.name -in $basics -and $_.status -ne 'PASS' }).Count) { throw 'Resolve the bot tenant, bot type and app identity checks before configuring the bot.' }
    $bot = $Audit.Bot
    $createBot = -not $bot
    if (-not $Audit.Connection -and $Audit.BlockSecrets) { throw 'An app management policy blocks new client secrets on the authentication app, so the OAuth connection cannot be created. Ask an administrator for an exemption, then rerun.' }
    if ($Settings.ConnectionName -eq $Settings.CurrentConnection) { throw 'Choose a separate SSO connection name so the current connection is preserved.' }
    $repairConnectionResource = Test-EratoLegacyResourceConnection $Audit.Connection $Settings
    if ($Audit.Connection -and -not (Test-EratoConnection $Audit.Connection $Settings) -and -not $repairConnectionResource) { throw 'The selected SSO connection already has different settings. Choose a new name or reconcile it manually; it will not be overwritten.' }
    $app = $Audit.App
    $desired = $app | ConvertTo-Json -Depth 50 | ConvertFrom-Json -AsHashtable
    $desired.identifierUris = @($desired.identifierUris | Where-Object { $null -ne $_ })
    if ($Settings.SsoResource -cnotin $desired.identifierUris) { $desired.identifierUris += $Settings.SsoResource }
    if (-not $desired.api) { $desired.api = @{} }
    $desired.api.requestedAccessTokenVersion = 2
    $scopes = @($desired.api.oauth2PermissionScopes | Where-Object { $null -ne $_ })
    $existing = @($scopes | Where-Object { $_.value -ceq 'access_as_user' })
    if ($existing.Count -gt 1) { throw 'Multiple access_as_user scopes exist; reconcile them before setup.' }
    if ($existing.Count) { $scope = $existing[0]; $scope.isEnabled = $true }
    else {
        $scope = @{ id = [guid]::NewGuid().ToString(); value = 'access_as_user'; type = 'User'; isEnabled = $true
            adminConsentDisplayName = 'Access Erato as the signed-in user'; adminConsentDescription = 'Allow Microsoft Teams to sign the user in to Erato.'
            userConsentDisplayName = 'Access Erato as you'; userConsentDescription = 'Allow Microsoft Teams to sign you in to Erato.' }
        $scopes += $scope
    }
    $desired.api.oauth2PermissionScopes = $scopes
    $clients = @($desired.api.preAuthorizedApplications | Where-Object { $null -ne $_ })
    foreach ($clientId in $script:TeamsClients) {
        $client = $clients | Where-Object { $_.appId -eq $clientId } | Select-Object -First 1
        if (-not $client) { $client = @{ appId = $clientId; delegatedPermissionIds = @() }; $clients += $client }
        if ($scope.id -notin $client.delegatedPermissionIds) { $client.delegatedPermissionIds = @($client.delegatedPermissionIds | Where-Object { $null -ne $_ }) + $scope.id }
    }
    $desired.api.preAuthorizedApplications = $clients
    if (-not $desired.web) { $desired.web = @{} }
    if ($script:Callback -cnotin $desired.web.redirectUris) { $desired.web.redirectUris = @($desired.web.redirectUris | Where-Object { $null -ne $_ }) + $script:Callback }
    $access = @($desired.requiredResourceAccess | Where-Object { $null -ne $_ })
    $graph = $access | Where-Object { $_.resourceAppId -eq $script:GraphAppId } | Select-Object -First 1
    if (-not $graph) { $graph = @{ resourceAppId = $script:GraphAppId; resourceAccess = @() }; $access += $graph }
    foreach ($name in $script:Scopes) {
        if (-not @($graph.resourceAccess | Where-Object { $_.id -eq $Audit.ScopeIds[$name] -and $_.type -eq 'Scope' }).Count) {
            $graph.resourceAccess = @($graph.resourceAccess | Where-Object { $null -ne $_ }) + @{ id = $Audit.ScopeIds[$name]; type = 'Scope' }
        }
    }
    $desired.requiredResourceAccess = $access
    $patch = @{}
    foreach ($key in @('identifierUris', 'api', 'web', 'requiredResourceAccess')) {
        if (($desired[$key] | ConvertTo-Json -Depth 50 -Compress) -cne ($app[$key] | ConvertTo-Json -Depth 50 -Compress)) { $patch[$key] = $desired[$key] }
    }
    if ($patch.web) {
        $web = @{}
        foreach ($key in @('homePageUrl', 'implicitGrantSettings', 'logoutUrl', 'redirectUris')) {
            if ($patch.web.ContainsKey($key)) { $web[$key] = $patch.web[$key] }
        }
        $patch.web = $web
    }
    return @{ registerProvider = (-not $Audit.ProviderRegistered); createBot = $createBot; botName = $Settings.BotName; resourceGroup = $Settings.ResourceGroup
        updateEndpoint = ($bot -and $bot.properties.endpoint -cne $Settings.MessagingEndpoint); currentEndpoint = $(if ($bot) { $bot.properties.endpoint })
        messagingEndpoint = $Settings.MessagingEndpoint; enableTeamsChannel = ($createBot -or 'msteams' -notin $bot.properties.enabledChannels)
        applicationPatch = $patch; createConnection = (-not $Audit.Connection); repairConnectionResource = $repairConnectionResource; connectionName = $Settings.ConnectionName
        credentialLifetimeDays = $Audit.SecretDays; ssoResource = $Settings.SsoResource; delegatedPermissions = $script:Scopes
        grantConsent = $(if ($Settings.SkipConsent) { @() } else { @($Audit.MissingConsent) }) }
}

<#
.SYNOPSIS
Returns whether the plan contains any Azure or Entra changes to apply.
#>
function Test-EratoPlanChanges {
    param($Plan)
    return [bool]($Plan.registerProvider -or $Plan.createBot -or $Plan.updateEndpoint -or $Plan.enableTeamsChannel -or $Plan.applicationPatch.Count -or
        $Plan.createConnection -or $Plan.repairConnectionResource -or $Plan.grantConsent.Count)
}

<#
.SYNOPSIS
Prints the public report's target, checks, proposed or completed changes, and remaining steps.
#>
function Write-EratoReport {
    param($Report)
    Write-Host "`nErato Teams bot — $($Report.mode)"
    Write-Host "Deployment:   $($Report.baseUrl)"
    Write-Host "Endpoint:     $($Report.messagingEndpoint)"
    Write-Host "Tenant:       $($Report.tenantId)"
    Write-Host "Subscription: $($Report.subscriptionId)"
    Write-Host "Bot:          $($Report.botName) ($($Report.botAppId))"
    Write-Host "Existing authentication app: $($Report.authAppId)"
    foreach ($check in $Report.checks) { Write-Host ("{0,-8} {1}: {2}" -f $check.status, $check.name, $check.detail) }
    if ($Report.plan) {
        Write-Host "`nProposed changes (review before applying):"
        $plan = $Report.plan
        $patch = $plan.applicationPatch
        if ($plan.registerProvider) { Write-Host '- Register the Microsoft.BotService resource provider in the subscription.' }
        if ($plan.createBot) { Write-Host "- Create single-tenant Azure Bot '$($plan.botName)' (Free F0, global) in resource group '$($plan.resourceGroup)' for app $($Report.botAppId)." }
        if ($plan.updateEndpoint) { Write-Host "- Change the messaging endpoint from '$($plan.currentEndpoint)' to '$($plan.messagingEndpoint)'." }
        elseif ($plan.createBot) { Write-Host "- Set the messaging endpoint to '$($plan.messagingEndpoint)'." }
        if ($plan.enableTeamsChannel) { Write-Host '- Enable the Microsoft Teams channel.' }
        if ($patch.identifierUris) { Write-Host "- Add Application ID URI: $($Report.plan.ssoResource)" }
        if ($patch.api) { Write-Host '- Enable v2 API access tokens and access_as_user; pre-authorize Teams desktop/mobile and web.' }
        if ($patch.web) { Write-Host "- Add Web callback: $script:Callback" }
        if ($patch.requiredResourceAccess) { Write-Host "- Add missing delegated Graph permissions from: $($Report.plan.delegatedPermissions -join ', ')" }
        if ($Report.plan.createConnection) { Write-Host "- Create OAuth connection '$($Report.plan.connectionName)' with a dedicated $($Report.plan.credentialLifetimeDays)-day credential." }
        if ($Report.plan.repairConnectionResource) { Write-Host "- Correct tokenExchangeUrl on OAuth connection '$($Report.plan.connectionName)' to '$($Report.plan.ssoResource)'; preserve its credential and other properties." }
        if ($plan.grantConsent.Count) { Write-Host "- Grant tenant-wide admin consent for: $($plan.grantConsent -join ', ')." }
        if (-not (Test-EratoPlanChanges $plan)) { Write-Host '- No Azure changes needed.' }
        Write-Host 'Existing app settings are preserved. Use -Json to inspect the full additive application patch.'
    }
    foreach ($change in $Report.changes) { Write-Host "APPLIED  $change" }
    Write-Host "`nStill to finish:"
    foreach ($step in $Report.remainingSteps) { Write-Host "- $step" }
    Write-Host "`n$($Report.note)"
}

<#
.SYNOPSIS
Validates settings and coordinates the read-only check, preview or confirmed Apply.
.DESCRIPTION
Returns the public report. WhatIf previews changes; Apply writes only after
ShouldProcess approval, re-reading state before writes and verifying it afterwards.
Failures report completed changes; a consent failure leaves other changes applied.
#>
function Invoke-EratoSetup {
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
    param([hashtable]$Settings, [switch]$Apply, [switch]$Json)
    $origin = $null
    if (-not [uri]::TryCreate($Settings.BaseUrl, [UriKind]::Absolute, [ref]$origin) -or
        $origin.Scheme -ne 'https' -or $origin.UserInfo -or $origin.Query -or $origin.Fragment -or $origin.AbsolutePath -ne '/') { throw 'BaseUrl must be an HTTPS origin without credentials, path or query.' }
    $Settings.BaseUrl = $origin.GetLeftPart([UriPartial]::Authority)
    if (-not $Settings.MessagingEndpoint) { $Settings.MessagingEndpoint = "$($Settings.BaseUrl)$script:MessagesPath" }
    $endpoint = $null
    if (-not [uri]::TryCreate($Settings.MessagingEndpoint, [UriKind]::Absolute, [ref]$endpoint) -or
        $endpoint.Scheme -ne 'https' -or $endpoint.UserInfo -or $endpoint.Query -or $endpoint.Fragment -or $endpoint.AbsolutePath -cne $script:MessagesPath) {
        throw "MessagingEndpoint must be an HTTPS URL ending in $script:MessagesPath, without credentials or query."
    }
    $Settings.MessagingEndpoint = $endpoint.GetLeftPart([UriPartial]::Authority) + $script:MessagesPath
    if (($Settings.ResourceGroup -and -not $Settings.BotName) -or ($Settings.BotName -and -not $Settings.ResourceGroup)) { throw 'Pass -ResourceGroup and -BotName together.' }
    if ($Settings.BotName -and $Settings.BotName -cnotmatch '^[A-Za-z0-9][A-Za-z0-9_.-]{1,62}$') { throw 'BotName may contain letters, digits, dots, hyphens and underscores (2-63 characters).' }
    if (-not $Settings.SsoResource) { $Settings.SsoResource = "api://$($origin.Authority)/botid-$($Settings.BotAppId)" }
    if ($Settings.SsoResource -cnotmatch '^api://[^\s]+$' -or $Settings.SsoResource.EndsWith('/access_as_user')) { throw 'SsoResource must be an Application ID URI starting with api://, without the scope suffix.' }
    $botSuffix = "botid-$($Settings.BotAppId)"
    if ($Settings.SsoResource -ine "api://$botSuffix" -and -not $Settings.SsoResource.EndsWith("/$botSuffix", [StringComparison]::OrdinalIgnoreCase)) {
        throw 'SsoResource must end with botid-<BotAppId>, even when AuthAppId uses a separate registration.'
    }
    $audit = Get-EratoAudit $Settings
    $report = $audit.Report
    if ($Apply -or $WhatIfPreference) {
        $plan = New-EratoSsoPlan $audit $Settings
        $report.mode = 'Preview'
        $report.plan = $plan
        # Always show the target and concrete plan before a confirmation prompt.
        if ($Apply -and -not $WhatIfPreference -and -not $Json) { Write-EratoReport $report }
        $target = "tenant $($Settings.TenantId), subscription $($Settings.SubscriptionId), bot $($report.botName), authentication app $($Settings.AuthAppId)"
        if ((Test-EratoPlanChanges $plan) -and $PSCmdlet.ShouldProcess($target, 'Apply the displayed Azure Bot, Entra, OAuth connection and consent changes')) {
            if (-not $Apply) { throw 'Use -Apply to configure the bot. A check never writes cloud settings.' }
            # Re-read immediately after confirmation. Shared apps may have gained
            # another environment's URI while the administrator reviewed the plan.
            $fresh = Get-EratoAudit $Settings
            $freshPlan = New-EratoSsoPlan $fresh $Settings
            $appUrl = "https://graph.microsoft.com/v1.0/applications/$($fresh.App.id)"
            $botUrl = "https://management.azure.com$($fresh.BotId)?api-version=$script:BotApiVersion"
            $report.mode = 'Apply'
            try {
                if ($freshPlan.registerProvider) {
                    $script:Step = 'registering Microsoft.BotService'
                    $providerUrl = "https://management.azure.com/subscriptions/$($Settings.SubscriptionId)/providers/Microsoft.BotService"
                    Invoke-EratoApi -Url "$providerUrl/register?api-version=2021-04-01" -Method POST -Body @{} | Out-Null
                    $registered = $false
                    for ($attempt = 0; $attempt -lt 24 -and -not $registered; $attempt++) {
                        $registered = (Invoke-EratoApi -Url "$providerUrl`?api-version=2021-04-01").registrationState -eq 'Registered'
                        if (-not $registered) { Start-Sleep -Seconds 5 }
                    }
                    if (-not $registered) { throw 'The Microsoft.BotService provider is still registering. Rerun Apply in a few minutes.' }
                    $report.changes += 'Registered the Microsoft.BotService resource provider.'
                }
                if ($freshPlan.createBot) {
                    $script:Step = 'creating the Azure Bot'
                    $properties = @{ displayName = $Settings.BotName; endpoint = $Settings.MessagingEndpoint; msaAppId = $Settings.BotAppId
                        msaAppType = 'SingleTenant'; msaAppTenantId = $Settings.TenantId }
                    $fresh.Bot = Invoke-EratoApi -Url $botUrl -Method PUT -Body @{ location = 'global'; kind = 'azurebot'; sku = @{ name = 'F0' }; properties = $properties }
                    $report.changes += "Created Azure Bot '$($Settings.BotName)' with messaging endpoint $($Settings.MessagingEndpoint)."
                    if (-not $Json) { Write-Host 'APPLIED  Azure Bot.' }
                } elseif ($freshPlan.updateEndpoint) {
                    $script:Step = 'updating the messaging endpoint'
                    # The update contract requires the bot's identity alongside the endpoint.
                    $current = $fresh.Bot.properties
                    $properties = @{ displayName = $(if ($current.displayName) { $current.displayName } else { $fresh.Bot.name }); endpoint = $Settings.MessagingEndpoint
                        msaAppId = $current.msaAppId; msaAppType = $current.msaAppType; msaAppTenantId = $current.msaAppTenantId }
                    Invoke-EratoApi -Url $botUrl -Method PATCH -Body @{ properties = $properties } | Out-Null
                    $report.changes += "Changed the messaging endpoint to $($Settings.MessagingEndpoint)."
                }
                if ($freshPlan.enableTeamsChannel) {
                    $script:Step = 'enabling the Teams channel'
                    $channelUrl = "https://management.azure.com$($fresh.BotId)/channels/MsTeamsChannel?api-version=$script:BotApiVersion"
                    Invoke-EratoApi -Url $channelUrl -Method PUT -Body @{ location = 'global'; properties = @{ channelName = 'MsTeamsChannel'; properties = @{ isEnabled = $true } } } | Out-Null
                    $report.changes += 'Enabled the Microsoft Teams channel.'
                }
                if ($freshPlan.createBot) {
                    # The OAuth connection belongs to the new bot.
                    $fresh.Connection = $null
                }
                # Graph validates pre-authorizations against scopes already saved
                # on the app, not scopes introduced in the same PATCH. Expose the
                # scope first, retaining existing pre-authorized clients, then
                # re-read and merge the remaining settings with its persisted ID.
                $enabledScope = @($fresh.App.api.oauth2PermissionScopes | Where-Object { $_.value -ceq 'access_as_user' -and $_.isEnabled })
                # Entra may only accept the new Application ID URI once the app
                # issues v2 tokens, so v2 and the scope are saved first, alone.
                if (-not $enabledScope.Count -or $fresh.App.api.requestedAccessTokenVersion -ne 2) {
                    $script:Step = 'saving v2 tokens and the access_as_user scope'
                    $scopeApi = $freshPlan.applicationPatch.api | ConvertTo-Json -Depth 50 | ConvertFrom-Json -AsHashtable
                    $scopeApi.preAuthorizedApplications = @($fresh.App.api.preAuthorizedApplications | Where-Object { $null -ne $_ })
                    Invoke-EratoApi -Url $appUrl -Method PATCH -Body @{ api = $scopeApi } | Out-Null
                    $report.changes += 'Enabled the access_as_user scope and v2 API tokens.'
                    if (-not $Json) { Write-Host 'APPLIED  Exposed API scope.' }
                    $fresh = Get-EratoAudit $Settings
                    if (@($fresh.App.api.oauth2PermissionScopes | Where-Object { $_.value -ceq 'access_as_user' -and $_.isEnabled }).Count -ne 1) {
                        throw 'The saved API scope is not visible yet. Rerun the check before retrying Apply; no OAuth credential has been created.'
                    }
                    $freshPlan = New-EratoSsoPlan $fresh $Settings
                }
                if ($freshPlan.applicationPatch.Count) {
                    $script:Step = 'updating the Entra app registration'
                    Invoke-EratoApi -Url $appUrl -Method PATCH -Body $freshPlan.applicationPatch | Out-Null
                    $report.changes += 'Added missing Entra SSO settings and delegated Graph permissions.'
                    if (-not $Json) { Write-Host 'APPLIED  Entra SSO settings.' }
                }
                if ($freshPlan.repairConnectionResource) {
                    $script:Step = 'repairing the OAuth connection'
                    $parameters = @($fresh.Connection.properties.parameters | ForEach-Object {
                        @{ key = $_.key; value = $(if ($_.key -eq 'tokenExchangeUrl') { $Settings.SsoResource } else { $_.value }) }
                    })
                    # PATCH only the provider parameters: do not read, replace
                    # or rotate the existing client secret.
                    Invoke-EratoApi -Url $fresh.ConnectionUrl -Method PATCH -Query $script:ConnectionQuery -Body @{ properties = @{ parameters = $parameters } } | Out-Null
                    $report.changes += "Corrected the token exchange URI on OAuth connection '$($Settings.ConnectionName)'; preserved its credential."
                }
                if ($freshPlan.createConnection) {
                    $script:Step = 'creating the OAuth connection credential'
                    $expiry = [DateTime]::UtcNow.AddDays($freshPlan.credentialLifetimeDays).ToString('yyyy-MM-ddTHH:mm:ssZ')
                    $label = "Erato Teams SSO $($fresh.Bot.name)/$($Settings.ConnectionName)"
                    $credential = Invoke-EratoApi -Url "$appUrl/addPassword" -Method POST -Body @{ passwordCredential = @{ displayName = $label; endDateTime = $expiry } }
                    if (-not $credential.secretText -or -not $credential.keyId) { throw "Credential creation returned an incomplete response. Inspect credentials named '$label' before retrying; Entra changes may already be applied." }
                    $properties = @{ clientId = $Settings.AuthAppId; clientSecret = $credential.secretText; serviceProviderId = $script:ProviderId
                        scopes = $script:Scopes -join ' '; parameters = @(@{ key = 'tenantId'; value = $Settings.TenantId }, @{ key = 'tokenExchangeUrl'; value = $Settings.SsoResource }) }
                    try {
                        $script:Step = 'creating the OAuth connection'
                        $location = $(if ($fresh.Bot.location) { $fresh.Bot.location } else { 'global' })
                        Invoke-EratoApi -Url $fresh.ConnectionUrl -Method PUT -Query $script:ConnectionQuery -Body @{ location = $location; properties = $properties } | Out-Null
                    } catch {
                        throw "OAuth creation failed after adding credential $($credential.keyId) ('$label', expires $expiry). Entra changes may already be applied. Inspect the connection and this credential before retrying. $($_.Exception.Message)"
                    } finally { $properties.Remove('clientSecret'); $credential.Remove('secretText') }
                    $report.credential = @{ keyId = $credential.keyId; displayName = $label; expiresAt = $expiry }
                    $report.changes += "Created OAuth connection '$($Settings.ConnectionName)'. Record credential $($credential.keyId), expiry $expiry, for rotation."
                }
                if ($freshPlan.grantConsent.Count) {
                    # Consent needs an Entra role this administrator may not hold.
                    # Everything above stays applied; the report links the consent page.
                    try {
                        $script:Step = 'granting admin consent'
                        $principalId = $fresh.AuthPrincipalId
                        if (-not $principalId) { $principalId = (Invoke-EratoApi -Url 'https://graph.microsoft.com/v1.0/servicePrincipals' -Method POST -Body @{ appId = $Settings.AuthAppId }).id }
                        if ($fresh.Grant) {
                            $scope = (@($fresh.Grant.scope -split '\s+' | Where-Object { $_ }) + @($freshPlan.grantConsent) | Select-Object -Unique) -join ' '
                            Invoke-EratoApi -Url "https://graph.microsoft.com/v1.0/oauth2PermissionGrants/$($fresh.Grant.id)" -Method PATCH -Body @{ scope = $scope } | Out-Null
                        } else {
                            Invoke-EratoApi -Url 'https://graph.microsoft.com/v1.0/oauth2PermissionGrants' -Method POST -Body @{ clientId = $principalId; consentType = 'AllPrincipals'
                                resourceId = $fresh.GraphPrincipalId; scope = $script:Scopes -join ' ' } | Out-Null
                        }
                        $report.changes += "Granted tenant-wide consent for: $($freshPlan.grantConsent -join ', ')."
                    } catch {
                        $report.consentError = "Consent was not granted: $($_.Exception.Message) An administrator can grant it at $($fresh.ConsentUrl)"
                        if (-not $Json) { Write-Host "NOT DONE $($report.consentError)" }
                    }
                }
                $verified = Get-EratoAudit $Settings
                # ARM can briefly return the previous connection after accepting
                # a PATCH/PUT. Re-read without repeating writes or credentials.
                for ($attempt = 0; $attempt -lt 3 -and -not (Test-EratoConnection $verified.Connection $Settings); $attempt++) {
                    Start-Sleep -Seconds 2
                    $verified = Get-EratoAudit $Settings
                }
                $report.checks = $verified.Report.checks
                $report.exitCode = $verified.Report.exitCode
                $report.remainingSteps = $verified.Report.remainingSteps
                $report.note = 'Azure changes applied and rechecked. Finish the remaining steps to verify the bot in Teams.'
                $report.Remove('plan')
            } catch {
                $completed = if ($report.changes.Count) { $report.changes -join ' ' } else { 'No writes confirmed.' }
                throw "Apply stopped. Completed: $completed $($_.Exception.Message)"
            }
        } else {
            $report.note = $(if (-not (Test-EratoPlanChanges $plan)) { 'No Azure changes needed. Complete the remaining Teams verification steps.' } else { 'No cloud changes made. Review the preview, then use -Apply when ready.' })
        }
    } else { $report.note = 'Read-only check. No cloud settings or credentials changed. ' + $report.note }
    return $report
}

if ($MyInvocation.InvocationName -ne '.') {
    try {
        if (-not (Get-Command az -ErrorAction SilentlyContinue)) { throw 'Azure CLI is required. Open Azure Cloud Shell and choose PowerShell.' }
        $settings = @{ TenantId = "$TenantId"; SubscriptionId = "$SubscriptionId"; BotAppId = "$BotAppId"; AuthAppId = "$AuthAppId"
            BaseUrl = $BaseUrl; MessagingEndpoint = $MessagingEndpoint; SsoResource = $SsoResource; CurrentConnection = $CurrentConnection; ConnectionName = $ConnectionName
            ResourceGroup = $ResourceGroup; BotName = $BotName; SkipConsent = [bool]$SkipConsent }
        $options = @{ Settings = $settings; Apply = $Apply; Json = $Json; WhatIf = $WhatIfPreference }
        if ($PSBoundParameters.ContainsKey('Confirm')) { $options.Confirm = $PSBoundParameters.Confirm }
        $report = Invoke-EratoSetup @options
        if ($Json) { $report | ConvertTo-Json -Depth 50 } else { Write-EratoReport $report }
        exit $report.exitCode
    } catch {
        # Do not print exception objects/stack traces that may retain credentials.
        $message = $_.Exception.Message
        if ($Json) { @{ mode = 'Blocked'; exitCode = 2; message = $message } | ConvertTo-Json }
        else { Write-Host "Setup stopped: $message"; Write-Host 'Some changes may have completed if Apply was started. Review the reported state before retrying.' }
        exit 2
    }
}
