apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-erato-app
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3130
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: erato-app
