apiVersion: v1
kind: Service
metadata:
  name: erato-backend
  labels:
    app: erato
spec:
  type: ClusterIP
  ports:
    - port: 3130
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: erato