pub const POSTGRES_QUERY_VERIFY_LATEST_MIGRATION: &str = "verify_latest_migration";
pub const POSTGRES_QUERY_LIST_RECENT_CHATS: &str = "list_recent_chats";
pub const POSTGRES_QUERY_COUNT_RECENT_CHATS: &str = "count_recent_chats";
pub const POSTGRES_QUERY_FREQUENT_ASSISTANTS: &str = "frequent_assistants";
pub const POSTGRES_QUERY_USER_SPENDING_BY_PROVIDER: &str = "user_spending_by_provider";
pub const POSTGRES_QUERY_GENERATION_START: &str = "generation_start";
pub const POSTGRES_QUERY_GENERATION_FINISH: &str = "generation_finish";
pub const POSTGRES_QUERY_GENERATION_HEARTBEAT: &str = "generation_heartbeat";
pub const POSTGRES_QUERY_GENERATION_REAP: &str = "generation_reap";
pub const POSTGRES_QUERY_GENERATION_CLEANUP: &str = "generation_cleanup";
pub const POSTGRES_QUERY_LIST_GENERATING_CHATS: &str = "list_generating_chats";
pub const POSTGRES_QUERY_SET_PENDING_TOOL_APPROVAL: &str = "set_pending_tool_approval";
pub const POSTGRES_QUERY_GENERATION_SHARED_START: &str = "generation_shared_start";
pub const POSTGRES_QUERY_GENERATION_SHARED_EVENT: &str = "generation_shared_event";
pub const POSTGRES_QUERY_GENERATION_SHARED_EVENTS: &str = "generation_shared_events";
pub const POSTGRES_QUERY_GENERATION_SHARED_COMMAND: &str = "generation_shared_command";
pub const POSTGRES_QUERY_GENERATION_SHARED_COMMANDS: &str = "generation_shared_commands";
pub const POSTGRES_QUERY_GENERATION_SHARED_COMMAND_CONSUME: &str =
    "generation_shared_command_consume";
pub const POSTGRES_QUERY_GENERATION_SHARED_FINISH: &str = "generation_shared_finish";
pub const POSTGRES_QUERY_GENERATION_SHARED_CLEANUP: &str = "generation_shared_cleanup";

pub const KNOWN_POSTGRES_QUERY_IDS: &[&str] = &[
    POSTGRES_QUERY_VERIFY_LATEST_MIGRATION,
    POSTGRES_QUERY_LIST_RECENT_CHATS,
    POSTGRES_QUERY_COUNT_RECENT_CHATS,
    POSTGRES_QUERY_FREQUENT_ASSISTANTS,
    POSTGRES_QUERY_USER_SPENDING_BY_PROVIDER,
    POSTGRES_QUERY_GENERATION_START,
    POSTGRES_QUERY_GENERATION_FINISH,
    POSTGRES_QUERY_GENERATION_HEARTBEAT,
    POSTGRES_QUERY_GENERATION_REAP,
    POSTGRES_QUERY_GENERATION_CLEANUP,
    POSTGRES_QUERY_LIST_GENERATING_CHATS,
    POSTGRES_QUERY_SET_PENDING_TOOL_APPROVAL,
    POSTGRES_QUERY_GENERATION_SHARED_START,
    POSTGRES_QUERY_GENERATION_SHARED_EVENT,
    POSTGRES_QUERY_GENERATION_SHARED_EVENTS,
    POSTGRES_QUERY_GENERATION_SHARED_COMMAND,
    POSTGRES_QUERY_GENERATION_SHARED_COMMANDS,
    POSTGRES_QUERY_GENERATION_SHARED_COMMAND_CONSUME,
    POSTGRES_QUERY_GENERATION_SHARED_FINISH,
    POSTGRES_QUERY_GENERATION_SHARED_CLEANUP,
];
