pub const POSTGRES_QUERY_VERIFY_LATEST_MIGRATION: &str = "verify_latest_migration";
pub const POSTGRES_QUERY_LIST_RECENT_CHATS: &str = "list_recent_chats";
pub const POSTGRES_QUERY_COUNT_RECENT_CHATS: &str = "count_recent_chats";
pub const POSTGRES_QUERY_FREQUENT_ASSISTANTS: &str = "frequent_assistants";
pub const POSTGRES_QUERY_USER_SPENDING_BY_PROVIDER: &str = "user_spending_by_provider";
pub const POSTGRES_QUERY_GENERATION_START: &str = "generation_start";
pub const POSTGRES_QUERY_GENERATION_FINISH: &str = "generation_finish";
pub const POSTGRES_QUERY_GENERATION_HEARTBEAT: &str = "generation_heartbeat";
pub const POSTGRES_QUERY_GENERATION_REAP: &str = "generation_reap";
pub const POSTGRES_QUERY_LIST_GENERATING_CHATS: &str = "list_generating_chats";

pub const KNOWN_POSTGRES_QUERY_IDS: &[&str] = &[
    POSTGRES_QUERY_VERIFY_LATEST_MIGRATION,
    POSTGRES_QUERY_LIST_RECENT_CHATS,
    POSTGRES_QUERY_COUNT_RECENT_CHATS,
    POSTGRES_QUERY_FREQUENT_ASSISTANTS,
    POSTGRES_QUERY_USER_SPENDING_BY_PROVIDER,
    POSTGRES_QUERY_GENERATION_START,
    POSTGRES_QUERY_GENERATION_FINISH,
    POSTGRES_QUERY_GENERATION_HEARTBEAT,
    POSTGRES_QUERY_GENERATION_REAP,
    POSTGRES_QUERY_LIST_GENERATING_CHATS,
];
