export {
  DesktopSidecarClient,
  MAX_BODY_BYTES,
  MAX_RESPONSE_BYTES,
  PROTOCOL_VERSIONS,
  createBrowserClientInfo,
  type DesktopSidecarClientOptions,
  type InvokeOptions,
  type InvokeProgressOptions,
  type SidecarCapability,
  type SidecarClientInfo,
  type SidecarReadinessState,
  type SidecarMethodContract,
  type SidecarSnapshot,
} from "./client.js";
export {
  SidecarClientError,
  SidecarRpcError,
  type SidecarClientErrorKind,
} from "./errors.js";
export {
  HttpTransport,
  type HttpTransportOptions,
  type SidecarFetch,
  type SidecarTransport,
  type SidecarTransportRequestOptions,
} from "./transport.js";
export type {
  CapabilityDescriptor,
  IndexingBenchmarkListV1Params,
  IndexingBenchmarkListV1Result,
  IndexingBenchmarkStartV1Params,
  IndexingBenchmarkStartV1Result,
  IndexingBenchmarkStatusV1Params,
  IndexingBenchmarkStatusV1Result,
  IndexingStartV1Params,
  IndexingStartV1Result,
  IndexingStopV1Params,
  IndexingStopV1Result,
  SearchQueryV1Params,
  SearchQueryV1Result,
  SearchMetadataFilter,
  SearchMetadataFieldsV1Params,
  SearchMetadataFieldsV1Result,
  IndexingResetV1Result,
  IndexingResetV1Params,
  IndexingStatusV1Result,
  IndexingStatusV1Params,
  CancelParams,
  CancelResult,
  DiagnosticsEchoV1Params,
  DiagnosticsEchoV1Result,
  DiscoverParams,
  DiscoverResult,
  DiscoveryDocument,
  JsonRpcEnvelope,
  OutlookAttachmentReference,
  OutlookConversationMessage,
  OutlookConversationWarning,
  OutlookEmailSummary,
  OutlookGetConversationV1Params,
  OutlookGetConversationV1Result,
  OutlookListingWarning,
  OutlookListEmailsV1Params,
  OutlookListEmailsV1Result,
  OutlookListMailboxesV1Params,
  OutlookListMailboxesV1Result,
  OutlookMailbox,
  OutlookMailboxReference,
  OutlookMessageReference,
  OutlookFileProvenance,
  OutlookMessageBody,
  OutlookMessageRecipient,
  OutlookSearchEmailsV1Params,
  OutlookSearchEmailsV1Result,
  OutlookSearchHit,
  SourceDescriptor,
  SourceFolderHierarchyNode,
  SourcesGetFolderHierarchyV1Params,
  SourcesGetFolderHierarchyV1Result,
  SourcesGetDocumentV1Params,
  SourcesGetDocumentV1Result,
  SourcesListV1Params,
  SourcesListV1Result,
  ProtocolErrorData,
  SidecarLocalTrace,
  SidecarLocalTraceStep,
  SidecarProgressV1Params,
  SidecarProgressV1Result,
  SidecarRestartV1Params,
  SidecarRestartV1Result,
  SidecarConfiguration,
  SidecarConfigureV1Params,
  SidecarConfigureV1Result,
} from "./generated/index.js";

export type {
  LocalTaskBinding,
  LocalTaskPlan,
  LocalTaskStatus,
  LocalDelegationSecurity,
  ApprovedLocalExport,
  LocalExportReceiptClaims,
  LocalContextClaims,
  LocalJobClaims,
  LocalContextsChallengeV1Params,
  LocalContextsChallengeV1Result,
  LocalContextsBindV1Params,
  LocalContextsBindV1Result,
  LocalTasksStartV1Params,
  LocalTasksStartV1Result,
  LocalTasksStatusV1Params,
  LocalTasksStatusV1Result,
  LocalTasksCancelV1Params,
  LocalTasksCancelV1Result,
  LocalTasksReviewV1Params,
  LocalTasksReviewV1Result,
  LocalExportsStatusV1Params,
  LocalExportsStatusV1Result,
  LocalExportsReadV1Params,
  LocalExportsReadV1Result,
  LocalExportsAckV1Params,
  LocalExportsAckV1Result,
} from "./generated/index.js";
export { supportsStrictLocalDelegation } from "./localDelegation.js";
export { validateOutlookFileProvenance } from "./generated/validators.mjs";
