export {
  DesktopSidecarClient,
  MAX_BODY_BYTES,
  MAX_RESPONSE_BYTES,
  PROTOCOL_VERSIONS,
  createBrowserClientInfo,
  type DesktopSidecarClientOptions,
  type InvokeOptions,
  type InvokeProgressOptions,
  type SidecarCapability,
  type SidecarClientInfo,
  type SidecarReadinessState,
  type SidecarMethodContract,
  type SidecarSnapshot,
} from "./client.js";
export {
  SidecarClientError,
  SidecarRpcError,
  type SidecarClientErrorKind,
} from "./errors.js";
export {
  HttpTransport,
  type HttpTransportOptions,
  type SidecarFetch,
  type SidecarTransport,
  type SidecarTransportRequestOptions,
} from "./transport.js";
export type {
  CapabilityDescriptor,
  IndexingBenchmarkListV1Params,
  IndexingBenchmarkListV1Result,
  IndexingBenchmarkStartV1Params,
  IndexingBenchmarkStartV1Result,
  IndexingBenchmarkStatusV1Params,
  IndexingBenchmarkStatusV1Result,
  IndexingStartV1Params,
  IndexingStartV1Result,
  IndexingStopV1Params,
  IndexingStopV1Result,
  SearchQueryV1Params,
  SearchQueryV1Result,
  IndexingResetV1Result,
  IndexingResetV1Params,
  IndexingStatusV1Result,
  IndexingStatusV1Params,
  CancelParams,
  CancelResult,
  DiagnosticsEchoV1Params,
  DiagnosticsEchoV1Result,
  DiscoverParams,
  DiscoverResult,
  DiscoveryDocument,
  JsonRpcEnvelope,
  OutlookAttachmentReference,
  OutlookConversationMessage,
  OutlookConversationWarning,
  OutlookEmailSummary,
  OutlookGetConversationV1Params,
  OutlookGetConversationV1Result,
  OutlookListingWarning,
  OutlookListEmailsV1Params,
  OutlookListEmailsV1Result,
  OutlookListMailboxesV1Params,
  OutlookListMailboxesV1Result,
  OutlookMailbox,
  OutlookMessageBody,
  OutlookMessageRecipient,
  OutlookSearchEmailsV1Params,
  OutlookSearchEmailsV1Result,
  OutlookSearchHit,
  ProtocolErrorData,
  SidecarLocalTrace,
  SidecarLocalTraceStep,
  SidecarProgressV1Params,
  SidecarProgressV1Result,
  SidecarRestartV1Params,
  SidecarRestartV1Result,
  SidecarConfiguration,
  SidecarConfigureV1Params,
  SidecarConfigureV1Result,
} from "./generated/index.js";
