default:
    just --list

install:
    pnpm install --no-frozen-lockfile --lockfile=false

build:
    pnpm run build

dev:
    pnpm run dev

storybook-live:
    pnpm run storybook:live

storybook-built:
    pnpm run storybook:built

build-storybook-live:
    pnpm run build-storybook:live

build-storybook-built:
    pnpm run build-storybook:built

type-check:
    pnpm run typecheck

format:
    pnpm run format

check-format:
    pnpm run format:check
