//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assistants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub owner_user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub prompt: String,
    pub mcp_server_ids: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_chat_provider: Option<String>,
    pub archived_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assistant_file_uploads::Entity")]
    AssistantFileUploads,
    #[sea_orm(has_many = "super::chats::Entity")]
    Chats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::assistant_file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantFileUploads.def()
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        super::assistant_file_uploads::Relation::FileUploads.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::assistant_file_uploads::Relation::Assistants
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
