//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_file_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_upload_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatId",
        to = "super::chats::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chats,
    #[sea_orm(
        belongs_to = "super::file_uploads::Entity",
        from = "Column::FileUploadId",
        to = "super::file_uploads::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FileUploads,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileUploads.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
