//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    #[sea_orm(column_type = "Text")]
    pub file_storage_provider_id: String,
    #[sea_orm(column_type = "Text")]
    pub file_storage_path: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assistant_file_uploads::Entity")]
    AssistantFileUploads,
    #[sea_orm(has_many = "super::chat_file_uploads::Entity")]
    ChatFileUploads,
}

impl Related<super::assistant_file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssistantFileUploads.def()
    }
}

impl Related<super::chat_file_uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatFileUploads.def()
    }
}

impl Related<super::assistants::Entity> for Entity {
    fn to() -> RelationDef {
        super::assistant_file_uploads::Relation::Assistants.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::assistant_file_uploads::Relation::FileUploads
                .def()
                .rev(),
        )
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_file_uploads::Relation::Chats.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_file_uploads::Relation::FileUploads.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
