//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::chats::Entity as Chats;
pub use super::file_uploads::Entity as FileUploads;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
