allowBuilds:
  esbuild: true
  protobufjs: true
  unrs-resolver: true
# 5 days delay
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - "@dukelib/sheets-wasm@0.1.21"
  - "@erato/frontend"
  - "@extend-ai/react-docx@0.7.0-alpha.2"
  - "@extend-ai/react-xlsx@0.15.0"
overrides:
  # A lot of packages depend on it, they make a lot of major version bumps and most are just about build env/packaging.
  uuid: 14.0.0
  # Dependency of `react-use` in `@erato/frontend`; See https://github.com/streamich/react-use & ERMAIN-327
  # Is only used on codepath that we don't use.
  js-cookie: 3.0.7
