apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "erato-local.fullname" . }}-azurite-pvc
  labels:
    {{- include "erato-local.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "erato-local.fullname" . }}-azurite
  labels:
    {{- include "erato-local.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10000
      targetPort: 10000
      protocol: TCP
      name: blob
    - port: 10001
      targetPort: 10001
      protocol: TCP
      name: queue
    - port: 10002
      targetPort: 10002
      protocol: TCP
      name: table
  selector:
    app.kubernetes.io/name: {{ include "erato-local.name" . }}-azurite
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erato-local.fullname" . }}-azurite
  labels:
    {{- include "erato-local.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erato-local.name" . }}-azurite
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erato-local.name" . }}-azurite
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: azurite
          image: "mcr.microsoft.com/azure-storage/azurite:3.34.0"
          command:
            - "azurite"
            - "--blobHost"
            - "0.0.0.0"
            - "--inMemoryPersistence"
          ports:
            - name: blob
              containerPort: 10000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "erato-local.fullname" . }}-azurite-pvc 