apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "erato-local.fullname" . }}-azurite-init
  labels:
    {{- include "erato-local.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erato-local.name" . }}-azurite-init
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-azurite
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 {{ include "erato-local.fullname" . }}-azurite 10000; do echo "$(date +"%Y-%m-%d %H:%M:%S") waiting for azurite..."; sleep 2; done;']
      containers:
        - name: create-container
          image: "mcr.microsoft.com/azure-cli:2.78.0"
          command: ["/bin/sh", "-c"]
          args:
            - >
              az storage container create --name erato-storage --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://{{ include "erato-local.fullname" . }}-azurite:10000/devstoreaccount1;" --public-access off --fail-on-exist > /dev/null 2>&1 || true 