{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dex
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-dex
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 5556
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-dex
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }} 