{{- if and .Values.dex.enabled .Values.dex.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dex
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-dex
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.dex.ingress.className }}
  {{- if .Values.dex.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.dex.ingress.host }}
      secretName: {{ .Values.dex.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.dex.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dex
                port:
                  name: http
{{- end }}
