apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-erato-toml-secret
data:
  erato.toml: {{ .Files.Get "config/erato.toml" | b64enc | quote }}
{{- if .Values.erato.backend.configFile.useAlt }}
  erato.alt.toml: {{ .Files.Get "config/erato.alt.toml" | b64enc | quote }}
{{- end }}