{{/*
Create Kubernetes Secrets for each scenario's generated configuration.
Only creates secrets for scenarios that have .auto.toml files present.
*/}}
{{- range $scenario := list "basic" "tight-budget" "assistants" "entra_id" }}
{{- $autoFile := printf "config/erato.scenario-%s.auto.toml" $scenario }}
{{- if $.Files.Glob $autoFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-erato-scenario-{{ $scenario | replace "_" "-" }}-secrets
  labels:
    {{- include "erato-local.labels" $ | nindent 4 }}
    app.kubernetes.io/component: config
    erato.dev/scenario: {{ $scenario }}
type: Opaque
stringData:
  erato.scenario.auto.toml: {{ $.Files.Get $autoFile | quote }}
{{- end }}
{{- end }}
