{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "erato-local.fullname" . }}-postgres
  labels:
    {{- include "erato-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  instances: {{ .Values.postgresql.instances }}
  imageName: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
  enableSuperuserAccess: true
  storage:
    size: {{ .Values.postgresql.storage.size }}
{{- end }}