name: Frontend Type & Lint Checks

on:
  pull_request:
    paths:
      - "frontend/**"
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  lint-and-typecheck:
    name: ESLint and TypeScript
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        working-directory: frontend
        run: pnpm install
      
      - name: Compile i18n messages
        working-directory: frontend
        run: pnpm run i18n:compile
      
      - name: Run ESLint
        working-directory: frontend
        run: pnpm run lint
      
      - name: Check Prettier formatting
        working-directory: frontend
        run: pnpm exec prettier --check .
      
      - name: Run TypeScript check
        working-directory: frontend
        run: pnpm run typecheck
      
      - name: Run strict lint (with type checking)
        working-directory: frontend
        run: pnpm run lint:strict
        continue-on-error: true  # This will not fail the build but will be reported 